'use client';

import type { CSSProperties, ReactNode } from 'react';

export const workspaceTheme = { page: '#eef2f6', surface: '#ffffff', surfaceSoft: '#f8fafc', border: '#d7e0ea', text: '#0f172a', muted: '#64748b', blue: '#1d4ed8', navy: '#0b2f6b', orange: '#f5a300', green: '#15803d', red: '#dc2626', amber: '#d97706', purple: '#7c3aed' };
export function PageFrame({ children, maxWidth = 1480 }: { children: ReactNode; maxWidth?: number }) { return <div style={{ width: '100%', maxWidth, margin: '0 auto', padding: '1.25rem clamp(0.9rem, 2vw, 1.6rem) 2.5rem' }}>{children}</div>; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', flexWrap: 'wrap', marginBottom: '1rem' }}><div style={{ minWidth: 0 }}>{eyebrow && <div style={{ color: workspaceTheme.blue, fontSize: '0.7rem', fontWeight: 850, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '0.28rem' }}>{eyebrow}</div>}<h1 style={{ margin: 0, color: workspaceTheme.text, fontSize: 'clamp(1.45rem, 2.3vw, 2rem)', lineHeight: 1.15 }}>{title}</h1>{description && <p style={{ margin: '0.42rem 0 0', color: workspaceTheme.muted, maxWidth: '850px', fontSize: '0.9rem', lineHeight: 1.5 }}>{description}</p>}</div>{actions && <div style={{ display: 'flex', alignItems: 'center', gap: '0.55rem', flexWrap: 'wrap' }}>{actions}</div>}</header>; }
export function ActionButton({ children, onClick, tone = 'primary', disabled = false, type = 'button' }: { children: ReactNode; onClick?: () => void; tone?: 'primary' | 'success' | 'warning' | 'danger' | 'secondary'; disabled?: boolean; type?: 'button' | 'submit' }) { const p = { primary: [workspaceTheme.blue, '#fff', workspaceTheme.blue], success: [workspaceTheme.green, '#fff', workspaceTheme.green], warning: [workspaceTheme.orange, '#111827', workspaceTheme.orange], danger: ['#fef2f2', workspaceTheme.red, '#fecaca'], secondary: ['#fff', workspaceTheme.text, workspaceTheme.border] }[tone]; return <button type={type} disabled={disabled} onClick={onClick} style={{ border: `1px solid ${p[2]}`, background: disabled ? '#cbd5e1' : p[0], color: disabled ? '#64748b' : p[1], borderRadius: '8px', padding: '0.58rem 0.88rem', fontSize: '0.78rem', fontWeight: 800, cursor: disabled ? 'not-allowed' : 'pointer' }}>{children}</button>; }
export function KpiGrid({ children }: { children: ReactNode }) { return <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '0.75rem', marginBottom: '1rem' }}>{children}</div>; }
export function KpiCard({ label, value, detail, tone = 'blue', onClick }: { label: string; value: ReactNode; detail?: ReactNode; tone?: 'blue' | 'green' | 'orange' | 'red' | 'purple' | 'navy'; onClick?: () => void }) { const color = { blue: workspaceTheme.blue, green: workspaceTheme.green, orange: workspaceTheme.orange, red: workspaceTheme.red, purple: workspaceTheme.purple, navy: workspaceTheme.navy }[tone]; return <button onClick={onClick} type="button" style={{ textAlign: 'left', background: '#fff', border: `1px solid ${workspaceTheme.border}`, borderTop: `3px solid ${color}`, borderRadius: '10px', padding: '0.8rem 0.85rem', minHeight: '104px', boxShadow: '0 5px 14px rgba(15,23,42,0.06)', cursor: onClick ? 'pointer' : 'default' }}><div style={{ color: workspaceTheme.muted, fontSize: '0.68rem', fontWeight: 850, textTransform: 'uppercase' }}>{label}</div><div style={{ marginTop: '0.3rem', color, fontSize: '1.7rem', fontWeight: 900 }}>{value}</div>{detail && <div style={{ color: workspaceTheme.muted, fontSize: '0.73rem', marginTop: '0.4rem' }}>{detail}</div>}</button>; }
export function Panel({ title, description, actions, children, style }: { title?: string; description?: string; actions?: ReactNode; children: ReactNode; style?: CSSProperties }) { return <section style={{ background: '#fff', border: `1px solid ${workspaceTheme.border}`, borderRadius: '11px', boxShadow: '0 5px 14px rgba(15,23,42,0.05)', overflow: 'hidden', ...style }}>{(title || description || actions) && <div style={{ display: 'flex', justifyContent: 'space-between', gap: '0.8rem', padding: '0.9rem 1rem', borderBottom: `1px solid ${workspaceTheme.border}`, flexWrap: 'wrap' }}><div>{title && <h2 style={{ margin: 0, color: workspaceTheme.text, fontSize: '1rem' }}>{title}</h2>}{description && <p style={{ margin: '0.25rem 0 0', color: workspaceTheme.muted, fontSize: '0.76rem' }}>{description}</p>}</div>{actions}</div>}<div style={{ padding: '1rem' }}>{children}</div></section>; }
export function TwoColumn({ children, rightWidth = 'minmax(300px, 0.85fr)' }: { children: ReactNode; rightWidth?: string }) { return <div style={{ display: 'grid', gridTemplateColumns: `minmax(0, 1.4fr) ${rightWidth}`, gap: '0.9rem', alignItems: 'start' }} className="xdrive-two-column">{children}</div>; }
export function StatusBadge({ value, tone }: { value: string; tone?: 'green' | 'blue' | 'orange' | 'red' | 'grey' | 'purple' }) { const l = value.toLowerCase(); const t = tone ?? (l.includes('delivered') || l.includes('active') || l.includes('approved') ? 'green' : l.includes('late') || l.includes('overdue') || l.includes('error') ? 'red' : l.includes('pending') || l.includes('waiting') ? 'orange' : 'blue'); const c = { green: ['#dcfce7', '#166534', '#bbf7d0'], blue: ['#dbeafe', '#1d4ed8', '#bfdbfe'], orange: ['#fef3c7', '#92400e', '#fde68a'], red: ['#fee2e2', '#b91c1c', '#fecaca'], grey: ['#f1f5f9', '#475569', '#e2e8f0'], purple: ['#f3e8ff', '#7e22ce', '#e9d5ff'] }[t]; return <span style={{ display: 'inline-flex', border: `1px solid ${c[2]}`, background: c[0], color: c[1], borderRadius: '999px', padding: '0.2rem 0.48rem', fontSize: '0.68rem', fontWeight: 800, textTransform: 'capitalize', whiteSpace: 'nowrap' }}>{value.replace(/_/g, ' ')}</span>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div style={{ minHeight: '180px', display: 'grid', placeItems: 'center', textAlign: 'center', padding: '2rem' }}><div><div style={{ width: 42, height: 42, borderRadius: 12, background: '#eff6ff', color: workspaceTheme.blue, display: 'grid', placeItems: 'center', margin: '0 auto 0.65rem', fontWeight: 900 }}>X</div><h3 style={{ margin: 0 }}>{title}</h3>{description && <p style={{ color: workspaceTheme.muted, fontSize: '0.78rem' }}>{description}</p>}{action}</div></div>; }
export function DataTable({ columns, rows, empty }: { columns: string[]; rows: ReactNode[][]; empty?: ReactNode }) { if (!rows.length) return <>{empty ?? <EmptyState title="No records found" />}</>; return <div style={{ width: '100%', overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', minWidth: Math.max(columns.length * 145, 680) }}><thead><tr>{columns.map(c => <th key={c} style={{ textAlign: 'left', padding: '0.65rem 0.7rem', fontSize: '0.66rem', textTransform: 'uppercase', background: '#f8fafc', borderBottom: `1px solid ${workspaceTheme.border}` }}>{c}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((v, j) => <td key={j} style={{ padding: '0.72rem 0.7rem', fontSize: '0.78rem', borderBottom: '1px solid #edf2f7', verticalAlign: 'top' }}>{v}</td>)}</tr>)}</tbody></table></div>; }
export function AlertBanner({ tone = 'warning', children }: { tone?: 'warning' | 'danger' | 'success' | 'info'; children: ReactNode }) { const s = { warning: ['#fffbeb', '#fde68a', '#92400e'], danger: ['#fef2f2', '#fecaca', '#991b1b'], success: ['#f0fdf4', '#bbf7d0', '#166534'], info: ['#eff6ff', '#bfdbfe', '#1e40af'] }[tone]; return <div style={{ background: s[0], border: `1px solid ${s[1]}`, color: s[2], borderRadius: 9, padding: '0.72rem 0.85rem', fontSize: '0.8rem', fontWeight: 650, marginBottom: '0.85rem' }}>{children}</div>; }
