export const SUPPLEMENTAL_LEGAL_LANGUAGES = ['ur','pa-guru','pa-shah','hi','bn','gu'] as const;
export type SupplementalLegalLanguage = typeof SUPPLEMENTAL_LEGAL_LANGUAGES[number];

export type SupplementalControlledLegalDocumentCode =
  | 'platform_terms'
  | 'membership_subscription_terms'
  | 'marketplace_transport_terms'
  | 'customer_shipper_terms'
  | 'broker_terms'
  | 'owner_driver_terms'
  | 'carrier_fleet_terms'
  | 'privacy_policy';

type Shared = {
  business: string;
  platformRole: string;
  booking: string;
  payment: string;
  amendments: string;
  evidence: string;
  law: string;
};

type Commercial = {
  paymentAck: string;
  buyerRisk: string;
  amendmentsExtras: string;
  collectionEvidence: string;
  brokerRole: string;
  carrierCompliance: string;
  subcontracting: string;
};

type Pack = {
  titles: Record<SupplementalControlledLegalDocumentCode,string>;
  intro: string;
  shared: Shared;
  headings: { business:string; platform:string; booking:string; payment:string; changes:string; evidence:string; law:string };
  membershipHeadings: string[];
  membershipBody: string[];
  privacyHeadings: string[];
  privacyBodies: string[];
  commercialHeadings: { paymentAck:string; buyerRisk:string; amendmentsExtras:string; collectionEvidence:string; brokerRole:string; carrierCompliance:string; subcontracting:string };
  commercial: Commercial;
};

export const SUPPLEMENTAL_LEGAL_LANGUAGE_LABELS: Record<SupplementalLegalLanguage,string> = {
  ur: 'اردو',
  'pa-guru': 'ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)',
  'pa-shah': 'پنجابی (شاہ مُکھی)',
  hi: 'हिन्दी',
  bn: 'বাংলা',
  gu: 'ગુજરાતી',
};

export const isSupplementalLegalLanguage = (value: unknown): value is SupplementalLegalLanguage =>
  typeof value === 'string' && (SUPPLEMENTAL_LEGAL_LANGUAGES as readonly string[]).includes(value);

export const isRtlSupplementalLegalLanguage = (value: unknown) => value === 'ur' || value === 'pa-shah';

const packs: Record<SupplementalLegalLanguage,Pack> = {
  ur: {
    titles: {
      platform_terms:'XDrive پلیٹ فارم کی شرائط',
      membership_subscription_terms:'رکنیت اور سبسکرپشن کی شرائط',
      marketplace_transport_terms:'مارکیٹ پلیس اور ٹرانسپورٹ تجارتی شرائط',
      customer_shipper_terms:'کسٹمر / شپر تجارتی شرائط',
      broker_terms:'ٹرانسپورٹ بروکر تجارتی شرائط',
      owner_driver_terms:'اونر ڈرائیور / کیریئر شرائط',
      carrier_fleet_terms:'کیریئر / فلیٹ تجارتی شرائط',
      privacy_policy:'رازداری کی پالیسی',
    },
    intro:'یہ کنٹرول شدہ ترجمہ XDrive کے متعلقہ قانونی معاہدے کے قواعد بیان کرتا ہے۔',
    shared: {
      business:'آپ XDrive کو کاروباری حیثیت میں استعمال کرتے ہیں اور اکاؤنٹ، شناخت اور تجارتی معلومات درست فراہم کرنا ضروری ہے۔ آپ کو اس کاروبار یا تنظیم کی طرف سے کام کرنے کا اختیار ہونا چاہیے جس کی نمائندگی اکاؤنٹ کرتا ہے۔',
      platformRole:'XDrive لاجسٹکس ٹیکنالوجی پلیٹ فارم اور مارکیٹ پلیس فراہم کرتا ہے۔ جب تک XDrive کسی مخصوص سروس کے لیے تحریری طور پر واضح طور پر دوسری صورت پر متفق نہ ہو، XDrive پلیٹ فارم صارفین کے درمیان بکنگ میں کیریئر، ٹرانسپورٹ خریدار، ادائیگی کرنے والا، آجر یا معاہدہ کرنے والی ٹرانسپورٹ پارٹی نہیں ہے۔',
      booking:'لوڈ کی پوسٹنگ بذات خود ٹرانسپورٹ معاہدہ نہیں ہے۔ کوٹ ایک پیشکش ہے۔ خریدار کی Award اس وقت تک زیر التوا رہتی ہے جب تک منتخب کیریئر XDrive ورک فلو میں حتمی بکنگ شرائط واضح طور پر قبول نہ کرے۔',
      payment:'بکنگ میں ٹرانسپورٹ خریدار یا آرڈر دینے والی پارٹی کے طور پر شناخت شدہ کاروبار، منظور شدہ قیمت، VAT، ادائیگی کی شرائط، مقررہ تاریخ اور منظور شدہ ایڈجسٹمنٹس کے مطابق کام انجام دینے والے کیریئر کو ادائیگی کا ذمہ دار ہے۔ یہ ذمہ داری اس بات پر منحصر نہیں کہ خریدار، بروکر یا آرڈر دینے والی پارٹی کو اپنے کسٹمر یا کسی تیسرے فریق سے ادائیگی ملی ہے یا نہیں۔',
      amendments:'قیمت، ادائیگی کی شرائط، راستہ، کارگو، وقت یا دیگر متفقہ تجارتی شرائط میں اہم تبدیلی متعلقہ ترمیم یا ایڈجسٹمنٹ ورک فلو میں ریکارڈ ہونی چاہیے۔ سابقہ معاہدہ اور ثبوت خاموشی سے اوور رائٹ نہیں کیے جا سکتے۔',
      evidence:'آپریشنل اسٹیٹس، ٹائم اسٹیمپس، پیغامات، کلیکشن اور ڈیلیوری ثبوت، تصاویر، دستخط، POD، انوائسز، ادائیگی ریکارڈ اور تنازعات سروس چلانے اور آڈٹ ٹریل برقرار رکھنے کے لیے بکنگ کے ساتھ محفوظ کیے جا سکتے ہیں۔',
      law:'یہ کاروباری شرائط انگلینڈ اور ویلز کے قانون کے تحت ہیں۔ کاروباری صارفین کے لیے انگلینڈ اور ویلز کی عدالتوں کو خصوصی دائرہ اختیار حاصل ہے، سوائے جہاں کوئی لازمی قانون دوسری صورت لاگو ہو۔',
    },
    headings:{business:'کاروباری حیثیت اور اختیار',platform:'XDrive کا کردار',booking:'بکنگ اور معاہدہ',payment:'ادائیگی کی ذمہ داری',changes:'تبدیلیاں اور ایڈجسٹمنٹس',evidence:'ثبوت اور آڈٹ ٹریل',law:'قانون اور دائرہ اختیار'},
    membershipHeadings:['اہلیت اور رسائی','مفت اور ادائیگی والے ادوار','تجدید اور منسوخی','ٹرانسپورٹ فیس'],
    membershipBody:[
      'رکنیت کی رسائی اور اہلیت XDrive میں دکھائے گئے پلان، onboarding اور compliance تقاضوں کے تابع ہے۔',
      'کوئی بھی مفت رسائی کا دور پروموشنل ہے اور اس کی نقد قدر نہیں۔ ادائیگی والی رکنیت صرف ظاہر کردہ پلان اور بلنگ انتظام کے تحت شروع ہوتی ہے۔',
      'ادائیگی والی رکنیت ظاہر کردہ سائیکل کے مطابق منسوخی تک تجدید ہو سکتی ہے۔ منسوخی مستقبل کی تجدید روکتی ہے لیکن عام طور پر شروع شدہ بلنگ مدت واپس نہیں کرتی، سوائے جہاں قانون یا XDrive ایسا لازم کرے۔',
      'موجودہ رکنیت ماڈل میں XDrive ٹرانسپورٹ کی قیمت سے فیصد کمیشن نہیں لیتا، جب تک کوئی مختلف تحریری پروڈکٹ واضح طور پر متعارف نہ کی جائے۔',
    ],
    privacyHeadings:['ہم کون سا ڈیٹا پراسیس کرتے ہیں','ٹرانسپورٹ آپریشن کا ڈیٹا','شیئرنگ اور افشا','محفوظ رکھنے کی مدت اور حقوق'],
    privacyBodies:[
      'XDrive اکاؤنٹس بنانے، محفوظ رکھنے اور سروس فراہم کرنے کے لیے شناخت، رابطہ، کمپنی، ڈیوائس اور سیکیورٹی ڈیٹا پراسیس کرتا ہے۔',
      'ٹرانسپورٹ آپریشنز میں کلیکشن اور ڈیلیوری رابطے، مقامات، پیغامات، تصاویر، دستخط، POD اور دیگر ثبوت شامل ہو سکتے ہیں۔ صارفین صرف قانونی، درست اور بکنگ سے متعلق ذاتی ڈیٹا فراہم کریں۔',
      'سروس چلانے، صارفین کی حفاظت یا قانون کی تعمیل کے لیے XDrive ضروری ڈیٹا مجاز بکنگ شرکاء، سروس فراہم کنندگان اور حکام کے ساتھ شیئر کر سکتا ہے۔',
      'ڈیٹا محفوظ رکھنے کی مدت ریکارڈ کی نوعیت، معاہداتی و قانونی ذمہ داریوں، تنازعات اور سیکیورٹی کی ضرورت پر منحصر ہے۔ حقوق سے متعلق درخواستیں عوامی Privacy Policy میں دیے گئے رابطوں کے ذریعے کی جا سکتی ہیں۔',
    ],
    commercialHeadings:{paymentAck:'ہر Award پر ادائیگی کی تصدیق',buyerRisk:'ٹرانسپورٹ خریدار رسک اور exposure کنٹرول',amendmentsExtras:'ترامیم اور منظور شدہ اضافی چارجز',collectionEvidence:'کلیکشن اور ڈیلیوری ثبوت',brokerRole:'بروکر کا کردار اور کیریئر کے سامنے ذمہ داریاں',carrierCompliance:'کیریئر compliance',subcontracting:'سب کنٹریکٹنگ اور آگے کی کارکردگی'},
    commercial:{
      paymentAck:'ہر بار جب ٹرانسپورٹ خریدار کسی کوٹ کو Award کرتا ہے، XDrive مجاز صارف سے تصدیق لیتا ہے کہ خریدار ٹرانسپورٹ سروس آرڈر کر رہا ہے اور منظور شدہ بکنگ شرائط اور مقررہ تاریخ کے مطابق منتخب کیریئر کو ادائیگی کا ذمہ دار ہے۔ یہ تصدیق صارف، وقت اور لاگو شرائط کے ورژن کے ساتھ ریکارڈ کی جاتی ہے۔',
      buyerRisk:'جب کاروبار ٹرانسپورٹ خریدار کے طور پر کام کرے، XDrive Publish اور Award پر رسک کنٹرول لگا سکتا ہے۔ نیا خریدار بطور ڈیفالٹ restricted mode میں ہو سکتا ہے، زیادہ سے زیادہ 3 فعال ٹرانسپورٹ commitments اور £2,500 outstanding exposure کے ساتھ، جب تک مجاز Platform Owner جائزہ یا override نہ کرے۔',
      amendmentsExtras:'اہم تجارتی تبدیلی یا اضافی چارج اصل معاہدے کو اوور رائٹ نہیں کر سکتا۔ جہاں counterparty approval ضروری ہو، ترمیم صرف مطلوبہ منظوری کے بعد مؤثر ہو گی۔ منظور شدہ waiting time، handball، redelivery، اضافی stops اور دوسرے extras قابلِ سراغ adjustments کے طور پر محفوظ رہتے ہیں۔',
      collectionEvidence:'XDrive بکنگ آگے بڑھنے سے پہلے verified collection اور delivery evidence مانگ سکتا ہے۔ Loaded سے پہلے verified collection handover اور کم از کم ایک collection photo درکار ہو سکتی ہے، زیادہ سے زیادہ 10 تصاویر تک۔ ثبوت حقیقی بکنگ سے متعلق ہونا چاہیے اور جعلی، دوبارہ استعمال شدہ یا گمراہ کن طور پر تبدیل نہیں ہونا چاہیے۔',
      brokerRole:'بروکر کو اپنے تجارتی کردار کو درست ظاہر کرنا چاہیے اور الگ کسٹمر انتظام کو اس طرح پیش نہیں کرنا چاہیے جیسے وہ کیریئر کے ساتھ معاہدہ بدل دیتا ہو۔ جہاں بروکر transport buyer یا ordering party ہو، وہ ریکارڈ شدہ کیریئر ادائیگی کی ذمہ داری برقرار رکھتا ہے۔',
      carrierCompliance:'کام انجام دینے والا کیریئر مناسب اور قانونی گاڑیوں و عملے کے استعمال اور ضروری licences، insurance، permissions اور compliance دستاویزات برقرار رکھنے کا ذمہ دار ہے۔ بکنگ قبول کرنا ان ذمہ داریوں کو ختم نہیں کرتا۔',
      subcontracting:'جہاں subcontracting کی اجازت ہو، اسے منظم کرنے والی پارٹی یہ غلط بیان نہیں کر سکتی کہ کام کون انجام دے گا اور اسے disclosure، insurance اور قانونی تقاضوں پر عمل کرنا ہوگا۔ متاثرہ فریقوں کی واضح منظوری کے بغیر subcontracting موجودہ ذمہ داری منتقل یا ختم نہیں کرتا۔',
    },
  },
  'pa-guru': {
    titles:{platform_terms:'XDrive ਪਲੇਟਫਾਰਮ ਦੀਆਂ ਸ਼ਰਤਾਂ',membership_subscription_terms:'ਮੈਂਬਰਸ਼ਿਪ ਅਤੇ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਦੀਆਂ ਸ਼ਰਤਾਂ',marketplace_transport_terms:'ਮਾਰਕੀਟਪਲੇਸ ਅਤੇ ਟਰਾਂਸਪੋਰਟ ਵਪਾਰਕ ਸ਼ਰਤਾਂ',customer_shipper_terms:'ਕਸਟਮਰ / ਸ਼ਿਪਰ ਵਪਾਰਕ ਸ਼ਰਤਾਂ',broker_terms:'ਟਰਾਂਸਪੋਰਟ ਬ੍ਰੋਕਰ ਵਪਾਰਕ ਸ਼ਰਤਾਂ',owner_driver_terms:'ਓਨਰ ਡਰਾਈਵਰ / ਕੈਰੀਅਰ ਸ਼ਰਤਾਂ',carrier_fleet_terms:'ਕੈਰੀਅਰ / ਫਲੀਟ ਵਪਾਰਕ ਸ਼ਰਤਾਂ',privacy_policy:'ਪਰਦੇਦਾਰੀ ਨੀਤੀ'},
    intro:'ਇਹ ਨਿਯੰਤਰਿਤ ਅਨੁਵਾਦ ਸੰਬੰਧਿਤ XDrive ਕਾਨੂੰਨੀ ਸਮਝੌਤੇ ਦੇ ਨਿਯਮ ਦਰਸਾਉਂਦਾ ਹੈ।',
    shared:{business:'ਤੁਸੀਂ XDrive ਨੂੰ ਕਾਰੋਬਾਰੀ ਸਮਰੱਥਾ ਵਿੱਚ ਵਰਤਦੇ ਹੋ ਅਤੇ ਖਾਤੇ, ਪਛਾਣ ਅਤੇ ਵਪਾਰਕ ਜਾਣਕਾਰੀ ਸਹੀ ਦੇਣੀ ਲਾਜ਼ਮੀ ਹੈ। ਜਿਸ ਕਾਰੋਬਾਰ ਜਾਂ ਸੰਗਠਨ ਦੀ ਨੁਮਾਇੰਦਗੀ ਖਾਤਾ ਕਰਦਾ ਹੈ, ਉਸ ਦੀ ਓਰੋਂ ਕੰਮ ਕਰਨ ਦਾ ਅਧਿਕਾਰ ਤੁਹਾਡੇ ਕੋਲ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',platformRole:'XDrive ਇੱਕ ਲਾਜਿਸਟਿਕਸ ਤਕਨਾਲੋਜੀ ਪਲੇਟਫਾਰਮ ਅਤੇ ਮਾਰਕੀਟਪਲੇਸ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ। ਜਦ ਤੱਕ ਕਿਸੇ ਖਾਸ ਸੇਵਾ ਲਈ XDrive ਲਿਖਤੀ ਰੂਪ ਵਿੱਚ ਹੋਰ ਨਾ ਮੰਨੇ, XDrive ਪਲੇਟਫਾਰਮ ਉਪਭੋਗਤਾਵਾਂ ਵਿਚਕਾਰ ਬੁਕਿੰਗ ਦਾ ਕੈਰੀਅਰ, ਟਰਾਂਸਪੋਰਟ ਖਰੀਦਦਾਰ, ਭੁਗਤਾਨਕਰਤਾ, ਨਿਯੋਗਤਾ ਜਾਂ ਕਰਾਰ ਪੱਖ ਨਹੀਂ ਹੈ।',booking:'ਲੋਡ ਪੋਸਟ ਕਰਨਾ ਆਪਣੇ ਆਪ ਵਿੱਚ ਟਰਾਂਸਪੋਰਟ ਕਰਾਰ ਨਹੀਂ। ਕੋਟ ਇੱਕ ਪੇਸ਼ਕਸ਼ ਹੈ। ਖਰੀਦਦਾਰ ਦੀ Award ਉਦੋਂ ਤੱਕ ਬਕਾਇਆ ਰਹਿੰਦੀ ਹੈ ਜਦ ਤੱਕ ਚੁਣਿਆ ਕੈਰੀਅਰ XDrive ਵਰਕਫਲੋ ਵਿੱਚ ਅੰਤਿਮ ਬੁਕਿੰਗ ਸ਼ਰਤਾਂ ਨੂੰ ਸਪਸ਼ਟ ਤੌਰ ਤੇ ਸਵੀਕਾਰ ਨਾ ਕਰੇ।',payment:'ਬੁਕਿੰਗ ਵਿੱਚ ਟਰਾਂਸਪੋਰਟ ਖਰੀਦਦਾਰ ਜਾਂ ਆਰਡਰ ਕਰਨ ਵਾਲੇ ਪੱਖ ਵਜੋਂ ਦਰਸਾਇਆ ਕਾਰੋਬਾਰ ਮਨਜ਼ੂਰ ਕੀਮਤ, VAT, ਭੁਗਤਾਨ ਦੀਆਂ ਸ਼ਰਤਾਂ, due date ਅਤੇ ਮਨਜ਼ੂਰ adjustments ਅਨੁਸਾਰ ਕੰਮ ਕਰਨ ਵਾਲੇ ਕੈਰੀਅਰ ਨੂੰ ਭੁਗਤਾਨ ਕਰਨ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਹੈ। ਇਹ ਜ਼ਿੰਮੇਵਾਰੀ ਇਸ ਗੱਲ ਤੇ ਨਿਰਭਰ ਨਹੀਂ ਕਿ ਖਰੀਦਦਾਰ, ਬ੍ਰੋਕਰ ਜਾਂ ਆਰਡਰ ਕਰਨ ਵਾਲੇ ਪੱਖ ਨੂੰ ਆਪਣੇ ਗਾਹਕ ਜਾਂ ਕਿਸੇ ਤੀਜੇ ਪੱਖ ਤੋਂ ਭੁਗਤਾਨ ਮਿਲਿਆ ਹੈ ਜਾਂ ਨਹੀਂ।',amendments:'ਕੀਮਤ, ਭੁਗਤਾਨ ਸ਼ਰਤਾਂ, ਰੂਟ, ਕਾਰਗੋ, ਸਮਾਂ ਜਾਂ ਹੋਰ ਸਹਿਮਤ ਵਪਾਰਕ ਸ਼ਰਤਾਂ ਵਿੱਚ ਮਹੱਤਵਪੂਰਨ ਤਬਦੀਲੀਆਂ ਲਾਗੂ amendment ਜਾਂ adjustment ਵਰਕਫਲੋ ਵਿੱਚ ਦਰਜ ਹੋਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ। ਪੁਰਾਣੇ ਸਮਝੌਤੇ ਅਤੇ ਸਬੂਤ ਚੁੱਪਚਾਪ overwrite ਨਹੀਂ ਕੀਤੇ ਜਾ ਸਕਦੇ।',evidence:'Operational status, timestamps, messages, collection ਅਤੇ delivery evidence, photos, signatures, POD, invoices, payment records ਅਤੇ disputes ਸੇਵਾ ਚਲਾਉਣ ਅਤੇ audit trail ਰੱਖਣ ਲਈ ਬੁਕਿੰਗ ਨਾਲ ਸੰਭਾਲੇ ਜਾ ਸਕਦੇ ਹਨ।',law:'ਇਹ ਵਪਾਰਕ ਸ਼ਰਤਾਂ England and Wales ਦੇ ਕਾਨੂੰਨ ਅਧੀਨ ਹਨ। ਕਾਰੋਬਾਰੀ ਉਪਭੋਗਤਾਵਾਂ ਲਈ England and Wales ਦੀਆਂ ਅਦਾਲਤਾਂ ਨੂੰ ਵਿਸ਼ੇਸ਼ ਅਧਿਕਾਰ ਹੈ, ਜਿੱਥੇ ਕੋਈ ਲਾਜ਼ਮੀ ਕਾਨੂੰਨ ਹੋਰ ਨਾ ਮੰਗੇ।'},
    headings:{business:'ਕਾਰੋਬਾਰੀ ਦਰਜਾ ਅਤੇ ਅਧਿਕਾਰ',platform:'XDrive ਦੀ ਭੂਮਿਕਾ',booking:'ਬੁਕਿੰਗ ਅਤੇ ਕਰਾਰ',payment:'ਭੁਗਤਾਨ ਦੀ ਜ਼ਿੰਮੇਵਾਰੀ',changes:'ਤਬਦੀਲੀਆਂ ਅਤੇ adjustments',evidence:'ਸਬੂਤ ਅਤੇ audit trail',law:'ਕਾਨੂੰਨ ਅਤੇ ਅਧਿਕਾਰ ਖੇਤਰ'},
    membershipHeadings:['ਯੋਗਤਾ ਅਤੇ ਪਹੁੰਚ','ਮੁਫ਼ਤ ਅਤੇ ਭੁਗਤਾਨ ਅਵਧੀਆਂ','ਨਵੀਨੀਕਰਨ ਅਤੇ ਰੱਦ ਕਰਨਾ','ਟਰਾਂਸਪੋਰਟ ਫੀਸ'],
    membershipBody:['ਮੈਂਬਰਸ਼ਿਪ ਪਹੁੰਚ ਅਤੇ ਯੋਗਤਾ XDrive ਵਿੱਚ ਦਰਸਾਏ plan, onboarding ਅਤੇ compliance requirements ਅਧੀਨ ਹੈ।','ਕੋਈ ਵੀ free access period promotional ਹੈ ਅਤੇ ਉਸ ਦੀ cash value ਨਹੀਂ। Paid membership ਕੇਵਲ ਦਰਸਾਏ plan ਅਤੇ billing arrangement ਅਨੁਸਾਰ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ।','Paid membership ਦਰਸਾਏ cycle ਅਨੁਸਾਰ cancellation ਤੱਕ renew ਹੋ ਸਕਦੀ ਹੈ। Cancellation future renewals ਰੋਕਦੀ ਹੈ ਪਰ ਆਮ ਤੌਰ ਤੇ ਸ਼ੁਰੂ ਹੋ ਚੁੱਕੀ billing period ਵਾਪਸ ਨਹੀਂ ਕਰਦੀ ਜਦ ਤੱਕ law ਜਾਂ XDrive ਹੋਰ ਨਾ ਮੰਗੇ।','ਮੌਜੂਦਾ membership model ਵਿੱਚ XDrive transport value ਤੋਂ percentage commission ਨਹੀਂ ਲੈਂਦਾ ਜਦ ਤੱਕ ਕੋਈ ਹੋਰ product ਲਿਖਤੀ ਰੂਪ ਵਿੱਚ ਸਪਸ਼ਟ ਤੌਰ ਤੇ ਨਾ ਲਿਆਂਦਾ ਜਾਵੇ।'],
    privacyHeadings:['ਅਸੀਂ ਕਿਹੜਾ ਡਾਟਾ process ਕਰਦੇ ਹਾਂ','ਟਰਾਂਸਪੋਰਟ operation ਡਾਟਾ','Sharing ਅਤੇ disclosures','Retention ਅਤੇ rights'],
    privacyBodies:['XDrive accounts ਬਣਾਉਣ, ਸੁਰੱਖਿਅਤ ਕਰਨ ਅਤੇ service ਦੇਣ ਲਈ identity, contact, company, device ਅਤੇ security data process ਕਰਦਾ ਹੈ।','Transport operations ਵਿੱਚ collection ਅਤੇ delivery contacts, locations, messages, photographs, signatures, POD ਅਤੇ ਹੋਰ evidence ਸ਼ਾਮਲ ਹੋ ਸਕਦੇ ਹਨ। Users ਸਿਰਫ਼ lawful, accurate ਅਤੇ booking ਨਾਲ relevant personal data ਹੀ ਦੇਣ।','Service ਚਲਾਉਣ, users ਦੀ ਰੱਖਿਆ ਜਾਂ law ਦੀ compliance ਲਈ XDrive ਲੋੜੀਂਦਾ data authorised booking participants, service providers ਅਤੇ authorities ਨਾਲ share ਕਰ ਸਕਦਾ ਹੈ।','Retention record ਦੀ ਕਿਸਮ, contractual ਅਤੇ legal obligations, dispute needs ਅਤੇ security requirements ਤੇ ਨਿਰਭਰ ਕਰਦੀ ਹੈ। Rights requests public Privacy Policy ਦੇ contact details ਰਾਹੀਂ ਕੀਤੀਆਂ ਜਾ ਸਕਦੀਆਂ ਹਨ।'],
    commercialHeadings:{paymentAck:'ਹਰ Award ਤੇ ਭੁਗਤਾਨ ਦੀ ਪੁਸ਼ਟੀ',buyerRisk:'ਟਰਾਂਸਪੋਰਟ ਖਰੀਦਦਾਰ risk ਅਤੇ exposure controls',amendmentsExtras:'Amendments ਅਤੇ ਮਨਜ਼ੂਰ extras',collectionEvidence:'Collection ਅਤੇ delivery evidence',brokerRole:'Broker ਦੀ ਭੂਮਿਕਾ ਅਤੇ carrier-facing obligations',carrierCompliance:'Carrier compliance',subcontracting:'Subcontracting ਅਤੇ onward performance'},
    commercial:{paymentAck:'ਹਰ ਵਾਰ transport buyer ਕਿਸੇ quote ਨੂੰ Award ਕਰਦਾ ਹੈ, XDrive authorised user ਤੋਂ ਪੁਸ਼ਟੀ ਲੈਂਦਾ ਹੈ ਕਿ buyer transport service order ਕਰ ਰਿਹਾ ਹੈ ਅਤੇ accepted booking terms ਅਤੇ due date ਅਨੁਸਾਰ awarded carrier ਨੂੰ pay ਕਰਨ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਹੈ। ਇਹ acknowledgement acting user, time ਅਤੇ applicable terms version ਨਾਲ record ਹੁੰਦੀ ਹੈ।',buyerRisk:'ਜਦ ਕਾਰੋਬਾਰ transport buyer ਵਜੋਂ ਕੰਮ ਕਰਦਾ ਹੈ, XDrive Publish ਅਤੇ Award ਤੇ buyer risk controls ਲਾਗੂ ਕਰ ਸਕਦਾ ਹੈ। ਨਵਾਂ buyer default restricted mode ਵਿੱਚ ਹੋ ਸਕਦਾ ਹੈ, ਵੱਧ ਤੋਂ ਵੱਧ 3 active transport commitments ਅਤੇ £2,500 outstanding transport exposure ਨਾਲ, ਜਦ ਤੱਕ authorised Platform Owner review ਜਾਂ override ਨਾ ਕਰੇ।',amendmentsExtras:'Material commercial change ਜਾਂ additional charge original agreement ਨੂੰ overwrite ਨਹੀਂ ਕਰ ਸਕਦਾ। ਜਿੱਥੇ counterparty approval ਲਾਜ਼ਮੀ ਹੈ, proposed amendment required counterparty ਦੀ acceptance ਤੋਂ ਬਾਅਦ ਹੀ effective ਹੁੰਦਾ ਹੈ। Approved waiting time, handball, redelivery, additional stops ਅਤੇ ਹੋਰ extras traceable adjustments ਵਜੋਂ retained ਰਹਿੰਦੇ ਹਨ।',collectionEvidence:'XDrive booking ਅੱਗੇ ਵਧਣ ਤੋਂ ਪਹਿਲਾਂ verified collection ਅਤੇ delivery evidence ਮੰਗ ਸਕਦਾ ਹੈ। Job ਨੂੰ Loaded mark ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ verified collection handover ਅਤੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ collection photo, ਵੱਧ ਤੋਂ ਵੱਧ 10 photos ਤੱਕ, ਲੋੜੀਂਦੇ ਹੋ ਸਕਦੇ ਹਨ। Evidence ਅਸਲੀ booking ਨਾਲ ਸੰਬੰਧਿਤ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ ਅਤੇ fabricated, reused ਜਾਂ misleading ਤਰੀਕੇ ਨਾਲ altered ਨਹੀਂ ਹੋ ਸਕਦਾ।',brokerRole:'Broker ਨੂੰ ਆਪਣੀ commercial role ਸਹੀ disclose ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ ਅਤੇ ਵੱਖਰੇ customer arrangement ਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਨਹੀਂ ਦਿਖਾਉਣਾ ਚਾਹੀਦਾ ਕਿ carrier-facing agreement ਬਦਲ ਗਿਆ। ਜਿੱਥੇ broker transport buyer ਜਾਂ ordering party ਹੈ, ਉਹ recorded carrier payment obligation ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਰਹਿੰਦਾ ਹੈ।',carrierCompliance:'Performing carrier suitable lawful vehicles ਅਤੇ personnel ਵਰਤਣ ਅਤੇ ਲੋੜੀਂਦੇ licences, insurance, permissions ਅਤੇ compliance documents ਕਾਇਮ ਰੱਖਣ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਹੈ। Booking accept ਕਰਨ ਨਾਲ ਇਹ obligations ਖਤਮ ਨਹੀਂ ਹੁੰਦੀਆਂ।',subcontracting:'ਜਿੱਥੇ subcontracting allowed ਹੈ, ਉਸਨੂੰ arrange ਕਰਨ ਵਾਲਾ ਪੱਖ ਇਹ ਗਲਤ ਨਹੀਂ ਦੱਸ ਸਕਦਾ ਕਿ ਕੰਮ ਕੌਣ ਕਰੇਗਾ ਅਤੇ disclosure, insurance ਅਤੇ legal requirements ਦੀ ਪਾਲਣਾ ਕਰੇਗਾ। Explicit agreement ਤੋਂ ਬਿਨਾਂ subcontracting existing contractual obligation transfer ਜਾਂ extinguish ਨਹੀਂ ਕਰਦੀ।'}
  },
  'pa-shah': {
    titles:{platform_terms:'XDrive پلیٹ فارم دیاں شرطاں',membership_subscription_terms:'ممبرشپ تے سبسکرپشن دیاں شرطاں',marketplace_transport_terms:'مارکیٹ پلیس تے ٹرانسپورٹ تجارتی شرطاں',customer_shipper_terms:'کسٹمر / شپر تجارتی شرطاں',broker_terms:'ٹرانسپورٹ بروکر تجارتی شرطاں',owner_driver_terms:'اونر ڈرائیور / کیریئر شرطاں',carrier_fleet_terms:'کیریئر / فلیٹ تجارتی شرطاں',privacy_policy:'پرائیویسی پالیسی'},
    intro:'ایہہ کنٹرول شدہ ترجمہ متعلقہ XDrive قانونی معاہدے دے اصول بیان کردا اے۔',
    shared:{business:'تسی XDrive نوں کاروباری حیثیت وچ ورتدے او تے اکاؤنٹ، شناخت تے تجارتی معلومات درست دینا ضروری اے۔ جس کاروبار یا تنظیم دی نمائندگی اکاؤنٹ کردا اے، اوہدے ولوں کم کرن دا اختیار تہاڈے کول ہونا چاہیدا اے۔',platformRole:'XDrive لاجسٹکس ٹیکنالوجی پلیٹ فارم تے مارکیٹ پلیس مہیا کردا اے۔ جد تک XDrive کسے خاص سروس لئی لکھتی طور تے ہور گل صاف نہ منے، XDrive صارفاں دی بکنگ وچ کیریئر، ٹرانسپورٹ خریدار، ادائیگی کرن والا، آجر یا کنٹریکٹنگ ٹرانسپورٹ پارٹی نئیں اے۔',booking:'لوڈ پوسٹ کرنا آپ اپنے آپ ٹرانسپورٹ کنٹریکٹ نئیں اے۔ Quote اک پیشکش اے۔ Buyer دی Award اوہدوں تک pending رہندی اے جدوں تک چنیا کیریئر XDrive workflow وچ final booking terms نوں واضح طور تے قبول نہ کرے۔',payment:'بکنگ وچ transport buyer یا ordering party طور درج کاروبار approved price، VAT، payment terms، due date تے approved adjustments دے مطابق performing carrier نوں payment دا ذمہ دار اے۔ ایہہ ذمہ داری اس گل تے منحصر نئیں کہ buyer، broker یا ordering party نوں اپنے customer یا ہور third party توں payment ملی اے یا نئیں۔',amendments:'Price، payment terms، route، cargo، timing یا ہور agreed commercial terms وچ اہم تبدیلی applicable amendment یا adjustment workflow وچ record ہونی چاہیدی اے۔ پرانے agreement records تے evidence نوں چپکے overwrite نئیں کیتا جا سکدا۔',evidence:'Operational statuses، timestamps، messages، collection تے delivery evidence، photographs، signatures، POD، invoices، payment records تے disputes service چلاؤن تے audit trail برقرار رکھن لئی booking نال محفوظ کیتے جا سکدے نیں۔',law:'ایہہ business terms England and Wales دے law دے تابع نیں۔ Business users لئی England and Wales دیاں courts نوں exclusive jurisdiction اے، جتھے کوئی mandatory rule ہور نہ ہووے۔'},
    headings:{business:'کاروباری حیثیت تے اختیار',platform:'XDrive دا کردار',booking:'بکنگ تے کنٹریکٹ',payment:'ادائیگی دی ذمہ داری',changes:'تبدیلیاں تے adjustments',evidence:'ثبوت تے audit trail',law:'قانون تے jurisdiction'},
    membershipHeadings:['اہلیت تے رسائی','مفت تے paid ادوار','Renewal تے cancellation','Transport fees'],
    membershipBody:['Membership access تے eligibility XDrive وچ دکھائے plan، onboarding تے compliance requirements دے تابع اے۔','کوئی وی free access period promotional اے تے cash value نئیں رکھدا۔ Paid membership صرف disclosed plan تے billing arrangement تحت شروع ہوندی اے۔','Paid membership disclosed cycle مطابق cancellation تک renew ہو سکدی اے۔ Cancellation future renewals روکدی اے پر عام طور تے شروع ہو چکی billing period reverse نئیں کردی، سوائے جتھے law یا XDrive ہور لازم کرے۔','Current membership model وچ XDrive transport value توں percentage commission نئیں لیندا، جد تک کوئی مختلف written product صاف طور تے introduce نہ کیتا جاوے۔'],
    privacyHeadings:['اسی کیہڑا data process کردے آں','Transport-operation data','Sharing تے disclosures','Retention تے rights'],
    privacyBodies:['XDrive accounts بنانے، protect کرن تے service دین لئی identity، contact، company، device تے security data process کردا اے۔','Transport operations وچ collection تے delivery contacts، locations، messages، photographs، signatures، POD تے ہور evidence شامل ہو سکدا اے۔ Users صرف lawful، accurate تے booking نال relevant personal data دین۔','Service چلاؤن، users دی حفاظت یا law دی compliance لئی XDrive ضروری data authorised booking participants، service providers تے authorities نال share کر سکدا اے۔','Retention record دی type، contractual تے legal obligations، dispute needs تے security requirements تے depend کردی اے۔ Rights requests public Privacy Policy دے contact details راہیں کیتیاں جا سکدیاں نیں۔'],
    commercialHeadings:{paymentAck:'ہر Award تے payment acknowledgement',buyerRisk:'Transport buyer risk تے exposure controls',amendmentsExtras:'Amendments تے approved extras',collectionEvidence:'Collection تے delivery evidence',brokerRole:'Broker role تے carrier-facing obligations',carrierCompliance:'Carrier compliance',subcontracting:'Subcontracting تے onward performance'},
    commercial:{paymentAck:'ہر واری transport buyer quote نوں Award کردا اے، XDrive authorised user توں confirm کرواندا اے کہ buyer transport service order کر رہا اے تے accepted booking terms تے due date مطابق awarded carrier نوں pay کرن دا ذمہ دار اے۔ ایہ acknowledgement acting user، time تے applicable terms version نال record ہوندی اے۔',buyerRisk:'جد business transport buyer طور کم کردا اے، XDrive Publish تے Award تے risk controls لا سکدا اے۔ New buyer default restricted mode وچ ہو سکدا اے، maximum 3 active transport commitments تے £2,500 outstanding transport exposure نال، جد تک authorised Platform Owner review یا override نہ کرے۔',amendmentsExtras:'Material commercial change یا additional charge original agreement نوں overwrite نئیں کر سکدا۔ جتھے counterparty approval لازم اے، proposed amendment required acceptance توں بعد ہی effective ہوندا اے۔ Approved waiting time، handball، redelivery، additional stops تے ہور extras traceable adjustments طور retained رہندے نیں۔',collectionEvidence:'XDrive booking اگے ودھن توں پہلاں verified collection تے delivery evidence منگ سکدا اے۔ Job نوں Loaded mark کرن توں پہلاں verified collection handover تے گھٹ توں گھٹ اک collection photo، ودھ توں ودھ 10 photos تک، لازم ہو سکدے نیں۔ Evidence اصل booking نال متعلق ہونا چاہیدا اے تے fabricated، reused یا misleading طور تے altered نئیں ہو سکدا۔',brokerRole:'Broker نوں اپنا commercial role درست disclose کرنا چاہیدا اے تے وکھرے customer arrangement نوں ایویں پیش نئیں کرنا چاہیدا جیویں carrier-facing agreement بدل گیا ہووے۔ جتھے broker transport buyer یا ordering party اے، او recorded carrier payment obligation لئی ذمہ دار رہندا اے۔',carrierCompliance:'Performing carrier suitable lawful vehicles تے personnel ورتن تے required licences، insurance، permissions تے compliance documents برقرار رکھن دا ذمہ دار اے۔ Booking accept کرن نال ایہ obligations ختم نئیں ہوندیاں۔',subcontracting:'جتھے subcontracting allowed اے، arrange کرن والی party ایہ غلط بیان نئیں کر سکدی کہ کم کون کرے گا تے disclosure، insurance تے legal requirements پوری کرے گی۔ Explicit agreement توں بغیر subcontracting existing contractual obligation transfer یا ختم نئیں کردی۔'}
  },
  hi: {
    titles:{platform_terms:'XDrive प्लेटफ़ॉर्म की शर्तें',membership_subscription_terms:'सदस्यता और सब्सक्रिप्शन की शर्तें',marketplace_transport_terms:'मार्केटप्लेस और परिवहन व्यापार शर्तें',customer_shipper_terms:'ग्राहक / शिपर व्यापार शर्तें',broker_terms:'परिवहन ब्रोकर व्यापार शर्तें',owner_driver_terms:'ओनर ड्राइवर / कैरियर शर्तें',carrier_fleet_terms:'कैरियर / फ्लीट व्यापार शर्तें',privacy_policy:'गोपनीयता नीति'},
    intro:'यह नियंत्रित अनुवाद संबंधित XDrive कानूनी समझौते के नियम बताता है।',
    shared:{business:'आप XDrive का उपयोग व्यावसायिक क्षमता में करते हैं और आपको खाता, पहचान तथा वाणिज्यिक जानकारी सही देनी होगी। जिस व्यवसाय या संगठन का यह खाता प्रतिनिधित्व करता है उसकी ओर से कार्य करने का अधिकार आपके पास होना चाहिए।',platformRole:'XDrive एक लॉजिस्टिक्स प्रौद्योगिकी प्लेटफ़ॉर्म और मार्केटप्लेस प्रदान करता है। जब तक किसी विशेष सेवा के लिए XDrive लिखित रूप में स्पष्ट रूप से अन्यथा सहमत न हो, XDrive प्लेटफ़ॉर्म उपयोगकर्ताओं के बीच बुकिंग में कैरियर, परिवहन खरीदार, भुगतानकर्ता, नियोक्ता या परिवहन अनुबंध पक्ष नहीं है।',booking:'लोड पोस्टिंग स्वयं परिवहन अनुबंध नहीं है। Quote एक प्रस्ताव है। खरीदार की Award तब तक लंबित रहती है जब तक चुना गया कैरियर XDrive workflow में अंतिम booking terms स्पष्ट रूप से स्वीकार न करे।',payment:'बुकिंग में transport buyer या ordering party के रूप में पहचाना गया व्यवसाय स्वीकृत कीमत, VAT treatment, payment terms, due date और approved adjustments के अनुसार performing carrier को भुगतान करने के लिए जिम्मेदार है। यह दायित्व इस बात पर निर्भर नहीं है कि buyer, broker या ordering party को अपने ग्राहक या किसी अन्य third party से भुगतान मिला है या नहीं।',amendments:'कीमत, payment terms, route, cargo, timing या अन्य सहमत commercial terms में महत्वपूर्ण बदलाव लागू amendment या adjustment workflow में दर्ज होना चाहिए। पुराने agreement records और evidence को चुपचाप overwrite नहीं किया जा सकता।',evidence:'Operational statuses, timestamps, messages, collection और delivery evidence, photographs, signatures, POD, invoices, payment records और disputes सेवा चलाने और audit trail बनाए रखने के लिए booking के साथ रखे जा सकते हैं।',law:'ये business terms England and Wales के कानून द्वारा शासित हैं। Business users के लिए England and Wales की courts को exclusive jurisdiction है, सिवाय जहाँ कोई अनिवार्य नियम अन्यथा लागू हो।'},
    headings:{business:'व्यावसायिक स्थिति और अधिकार',platform:'XDrive की भूमिका',booking:'बुकिंग और अनुबंध',payment:'भुगतान दायित्व',changes:'बदलाव और adjustments',evidence:'साक्ष्य और audit trail',law:'कानून और अधिकार क्षेत्र'},
    membershipHeadings:['पात्रता और पहुँच','मुफ़्त और भुगतान अवधि','नवीनीकरण और रद्दीकरण','परिवहन शुल्क'],
    membershipBody:['Membership access और eligibility XDrive में दिखाए गए plan, onboarding और compliance requirements के अधीन हैं।','कोई भी free access period promotional है और उसका cash value नहीं है। Paid membership केवल disclosed plan और billing arrangement के अनुसार शुरू होती है।','Paid membership disclosed cycle के अनुसार cancellation तक renew हो सकती है। Cancellation future renewals रोकती है, पर सामान्यतः शुरू हो चुकी billing period को reverse नहीं करती, जब तक law या XDrive अन्यथा आवश्यक न करे।','वर्तमान membership model में XDrive transport value पर percentage commission नहीं लेता, जब तक कोई अलग written product स्पष्ट रूप से शुरू न किया जाए।'],
    privacyHeadings:['हम कौन-सा डेटा process करते हैं','Transport-operation data','Sharing और disclosures','Retention और rights'],
    privacyBodies:['XDrive accounts बनाने, सुरक्षित रखने और service देने के लिए identity, contact, company, device और security data process करता है।','Transport operations में collection और delivery contacts, locations, messages, photographs, signatures, POD और अन्य evidence शामिल हो सकते हैं। Users केवल lawful, accurate और booking से relevant personal data दें।','Service चलाने, users की रक्षा या law का पालन करने के लिए XDrive आवश्यक data authorised booking participants, service providers और authorities से share कर सकता है।','Retention record के प्रकार, contractual और legal obligations, dispute needs और security requirements पर निर्भर करता है। Rights requests public Privacy Policy में दिए contact details द्वारा की जा सकती हैं।'],
    commercialHeadings:{paymentAck:'प्रत्येक Award पर भुगतान पुष्टि',buyerRisk:'Transport buyer risk और exposure controls',amendmentsExtras:'Amendments और approved extras',collectionEvidence:'Collection और delivery evidence',brokerRole:'Broker role और carrier-facing obligations',carrierCompliance:'Carrier compliance',subcontracting:'Subcontracting और onward performance'},
    commercial:{paymentAck:'जब भी transport buyer किसी quote को Award करता है, XDrive authorised user से पुष्टि कराता है कि buyer transport service order कर रहा है और accepted booking terms तथा due date के अनुसार awarded carrier को pay करने के लिए जिम्मेदार है। यह acknowledgement acting user, time और applicable terms version के साथ record होती है।',buyerRisk:'जब business transport buyer की भूमिका में हो, XDrive Publish और Award पर risk controls लगा सकता है। New buyer default restricted mode में हो सकता है, अधिकतम 3 active transport commitments और £2,500 outstanding transport exposure के साथ, जब तक authorised Platform Owner review या override न करे।',amendmentsExtras:'Material commercial change या additional charge original agreement को overwrite नहीं कर सकता। जहाँ counterparty approval आवश्यक है, proposed amendment required acceptance के बाद ही effective होगा। Approved waiting time, handball, redelivery, additional stops और अन्य extras traceable adjustments के रूप में retained रहते हैं।',collectionEvidence:'XDrive booking आगे बढ़ने से पहले verified collection और delivery evidence माँग सकता है। Job को Loaded mark करने से पहले verified collection handover और कम से कम एक collection photo, अधिकतम 10 photos तक, आवश्यक हो सकते हैं। Evidence वास्तविक booking से संबंधित होना चाहिए और fabricated, reused या misleading तरीके से altered नहीं होना चाहिए।',brokerRole:'Broker को अपना commercial role सही disclose करना चाहिए और अलग customer arrangement को ऐसे प्रस्तुत नहीं करना चाहिए मानो carrier-facing agreement बदल गया हो। जहाँ broker transport buyer या ordering party है, वह recorded carrier payment obligation के लिए जिम्मेदार रहता है।',carrierCompliance:'Performing carrier suitable lawful vehicles और personnel के उपयोग तथा required licences, insurance, permissions और compliance documents बनाए रखने के लिए जिम्मेदार है। Booking स्वीकार करने से ये obligations समाप्त नहीं होते।',subcontracting:'जहाँ subcontracting allowed है, उसे arrange करने वाली party यह गलत नहीं बता सकती कि काम कौन करेगा और उसे disclosure, insurance तथा legal requirements का पालन करना होगा। Explicit agreement के बिना subcontracting existing contractual obligation transfer या समाप्त नहीं करती।'}
  },
  bn: {
    titles:{platform_terms:'XDrive প্ল্যাটফর্মের শর্তাবলি',membership_subscription_terms:'সদস্যপদ ও সাবস্ক্রিপশনের শর্তাবলি',marketplace_transport_terms:'মার্কেটপ্লেস ও পরিবহন বাণিজ্যিক শর্তাবলি',customer_shipper_terms:'কাস্টমার / শিপার বাণিজ্যিক শর্তাবলি',broker_terms:'পরিবহন ব্রোকার বাণিজ্যিক শর্তাবলি',owner_driver_terms:'ওনার ড্রাইভার / ক্যারিয়ার শর্তাবলি',carrier_fleet_terms:'ক্যারিয়ার / ফ্লিট বাণিজ্যিক শর্তাবলি',privacy_policy:'গোপনীয়তা নীতি'},
    intro:'এই নিয়ন্ত্রিত অনুবাদ সংশ্লিষ্ট XDrive আইনি চুক্তির নিয়ম বর্ণনা করে।',
    shared:{business:'আপনি ব্যবসায়িক উদ্দেশ্যে XDrive ব্যবহার করেন এবং অ্যাকাউন্ট, পরিচয় ও বাণিজ্যিক তথ্য সঠিকভাবে দিতে হবে। অ্যাকাউন্ট যে ব্যবসা বা প্রতিষ্ঠানের প্রতিনিধিত্ব করে তার পক্ষে কাজ করার অনুমতি আপনার থাকতে হবে।',platformRole:'XDrive একটি লজিস্টিকস প্রযুক্তি প্ল্যাটফর্ম ও মার্কেটপ্লেস সরবরাহ করে। নির্দিষ্ট কোনো সেবার জন্য XDrive লিখিতভাবে স্পষ্টভাবে অন্যথা সম্মত না হলে, প্ল্যাটফর্ম ব্যবহারকারীদের মধ্যে বুকিংয়ে XDrive ক্যারিয়ার, transport buyer, payer, employer বা contracting transport party নয়।',booking:'লোড পোস্ট করা নিজে পরিবহন চুক্তি নয়। Quote একটি প্রস্তাব। নির্বাচিত carrier XDrive workflow-এ final booking terms স্পষ্টভাবে গ্রহণ না করা পর্যন্ত buyer-এর Award pending থাকে।',payment:'বুকিংয়ে transport buyer বা ordering party হিসেবে চিহ্নিত ব্যবসা accepted price, VAT treatment, payment terms, due date এবং approved adjustments অনুযায়ী performing carrier-কে payment দেওয়ার জন্য দায়ী। buyer, broker বা ordering party তার নিজস্ব customer বা অন্য third party-এর কাছ থেকে payment পেয়েছে কি না তার উপর এই দায় নির্ভর করে না।',amendments:'Price, payment terms, route, cargo, timing বা অন্য agreed commercial terms-এ material change প্রযোজ্য amendment বা adjustment workflow-এ record করতে হবে। Historical agreement records এবং evidence নীরবে overwrite করা যাবে না।',evidence:'Operational statuses, timestamps, messages, collection ও delivery evidence, photographs, signatures, POD, invoices, payment records এবং disputes service পরিচালনা ও audit trail বজায় রাখতে booking-এর সঙ্গে রাখা যেতে পারে।',law:'এই business terms England and Wales-এর law দ্বারা governed। Business users-এর জন্য England and Wales-এর courts-এর exclusive jurisdiction থাকবে, কোনো mandatory rule অন্যভাবে প্রযোজ্য হলে তা ব্যতিক্রম।'},
    headings:{business:'ব্যবসায়িক অবস্থা ও ক্ষমতা',platform:'XDrive-এর ভূমিকা',booking:'বুকিং ও চুক্তি',payment:'পেমেন্টের দায়',changes:'পরিবর্তন ও adjustments',evidence:'প্রমাণ ও audit trail',law:'আইন ও jurisdiction'},
    membershipHeadings:['যোগ্যতা ও অ্যাক্সেস','বিনামূল্য ও paid সময়কাল','Renewal ও cancellation','Transport fees'],
    membershipBody:['Membership access ও eligibility XDrive-এ প্রদর্শিত plan, onboarding এবং compliance requirements-এর অধীন।','যেকোনো free access period promotional এবং এর cash value নেই। Paid membership কেবল disclosed plan ও billing arrangement অনুযায়ী শুরু হয়।','Paid membership disclosed cycle অনুযায়ী cancellation পর্যন্ত renew হতে পারে। Cancellation future renewals বন্ধ করে, কিন্তু সাধারণত শুরু হয়ে যাওয়া billing period reverse করে না, যদি না law বা XDrive তা প্রয়োজন করে।','বর্তমান membership model-এ XDrive transport value-এর ওপর percentage commission নেয় না, যদি না আলাদা written product স্পষ্টভাবে চালু করা হয়।'],
    privacyHeadings:['আমরা কোন data process করি','Transport-operation data','Sharing ও disclosures','Retention ও rights'],
    privacyBodies:['XDrive accounts তৈরি, সুরক্ষিত রাখা এবং service দিতে identity, contact, company, device এবং security data process করে।','Transport operations-এ collection ও delivery contacts, locations, messages, photographs, signatures, POD এবং অন্যান্য evidence থাকতে পারে। Users কেবল lawful, accurate এবং booking-এর সঙ্গে relevant personal data দেবে।','Service চালানো, users-কে রক্ষা করা বা law মেনে চলার জন্য XDrive প্রয়োজনীয় data authorised booking participants, service providers এবং authorities-এর সঙ্গে share করতে পারে।','Retention record-এর ধরন, contractual ও legal obligations, dispute needs এবং security requirements-এর উপর নির্ভর করে। Rights requests public Privacy Policy-এর contact details-এর মাধ্যমে করা যায়।'],
    commercialHeadings:{paymentAck:'প্রতি Award-এ payment acknowledgement',buyerRisk:'Transport buyer risk ও exposure controls',amendmentsExtras:'Amendments ও approved extras',collectionEvidence:'Collection ও delivery evidence',brokerRole:'Broker role ও carrier-facing obligations',carrierCompliance:'Carrier compliance',subcontracting:'Subcontracting ও onward performance'},
    commercial:{paymentAck:'প্রতিবার transport buyer কোনো quote Award করলে XDrive authorised user-কে confirm করতে বলে যে buyer transport service order করছে এবং accepted booking terms ও due date অনুযায়ী awarded carrier-কে pay করার জন্য দায়ী। এই acknowledgement acting user, time এবং applicable terms version-এর সঙ্গে record হয়।',buyerRisk:'Business transport buyer হিসেবে কাজ করলে XDrive Publish ও Award-এ risk controls প্রয়োগ করতে পারে। New buyer default restricted mode-এ থাকতে পারে, সর্বোচ্চ 3 active transport commitments এবং £2,500 outstanding transport exposure সহ, যতক্ষণ না authorised Platform Owner review বা override করে।',amendmentsExtras:'Material commercial change বা additional charge original agreement overwrite করতে পারে না। যেখানে counterparty approval দরকার, proposed amendment required acceptance-এর পরেই effective হবে। Approved waiting time, handball, redelivery, additional stops এবং অন্য extras traceable adjustments হিসেবে retained থাকে।',collectionEvidence:'XDrive booking এগোনোর আগে verified collection ও delivery evidence চাইতে পারে। Job Loaded mark করার আগে verified collection handover এবং অন্তত একটি collection photo, সর্বোচ্চ 10 photos পর্যন্ত, প্রয়োজন হতে পারে। Evidence আসল booking-এর সঙ্গে সম্পর্কিত হতে হবে এবং fabricated, reused বা misleadingভাবে altered হতে পারবে না।',brokerRole:'Broker-কে তার commercial role সঠিকভাবে disclose করতে হবে এবং আলাদা customer arrangement-কে এমনভাবে উপস্থাপন করা যাবে না যেন carrier-facing agreement বদলে গেছে। যেখানে broker transport buyer বা ordering party, সে recorded carrier payment obligation-এর জন্য দায়ী থাকবে।',carrierCompliance:'Performing carrier suitable lawful vehicles ও personnel ব্যবহার এবং required licences, insurance, permissions ও compliance documents বজায় রাখার জন্য দায়ী। Booking accept করলে এসব obligations শেষ হয় না।',subcontracting:'যেখানে subcontracting allowed, তা arrange করা party কাজ কে করবে সে বিষয়ে ভুল তথ্য দিতে পারবে না এবং disclosure, insurance ও legal requirements মানতে হবে। Explicit agreement ছাড়া subcontracting existing contractual obligation transfer বা শেষ করে না।'}
  },
  gu: {
    titles:{platform_terms:'XDrive પ્લેટફોર્મની શરતો',membership_subscription_terms:'સભ્યપદ અને સબ્સ્ક્રિપ્શનની શરતો',marketplace_transport_terms:'માર્કેટપ્લેસ અને ટ્રાન્સપોર્ટ વ્યાપારી શરતો',customer_shipper_terms:'કસ્ટમર / શિપર વ્યાપારી શરતો',broker_terms:'ટ્રાન્સપોર્ટ બ્રોકર વ્યાપારી શરતો',owner_driver_terms:'ઓનર ડ્રાઇવર / કેરિયર શરતો',carrier_fleet_terms:'કેરિયર / ફ્લીટ વ્યાપારી શરતો',privacy_policy:'ગોપનીયતા નીતિ'},
    intro:'આ નિયંત્રિત અનુવાદ સંબંધિત XDrive કાનૂની કરારના નિયમો દર્શાવે છે.',
    shared:{business:'તમે XDrive નો ઉપયોગ વ્યવસાયિક હેતુથી કરો છો અને એકાઉન્ટ, ઓળખ તથા વ્યાપારી માહિતી ચોક્કસ આપવી જરૂરી છે. એકાઉન્ટ જે વ્યવસાય અથવા સંસ્થાનું પ્રતિનિધિત્વ કરે છે તેની તરફથી કાર્ય કરવાનો અધિકાર તમારી પાસે હોવો જોઈએ.',platformRole:'XDrive લોજિસ્ટિક્સ ટેકનોલોજી પ્લેટફોર્મ અને માર્કેટપ્લેસ આપે છે. કોઈ વિશિષ્ટ સેવા માટે XDrive લેખિતમાં સ્પષ્ટ રીતે અન્યથા સંમત ન થાય ત્યાં સુધી, પ્લેટફોર્મ વપરાશકર્તાઓ વચ્ચેની booking માં XDrive carrier, transport buyer, payer, employer અથવા contracting transport party નથી.',booking:'Load post કરવું પોતે transport contract નથી. Quote એક offer છે. પસંદ કરાયેલ carrier XDrive workflow માં final booking terms સ્પષ્ટ રીતે accept ન કરે ત્યાં સુધી buyer ની Award pending રહે છે.',payment:'Booking માં transport buyer અથવા ordering party તરીકે ઓળખાયેલ business accepted price, VAT treatment, payment terms, due date અને approved adjustments અનુસાર performing carrier ને payment કરવા જવાબદાર છે. buyer, broker અથવા ordering party ને પોતાના customer અથવા અન્ય third party પાસેથી payment મળ્યું છે કે નહીં તેના પર આ જવાબદારી આધારિત નથી.',amendments:'Price, payment terms, route, cargo, timing અથવા અન્ય agreed commercial terms માં material change લાગુ amendment અથવા adjustment workflow માં record થવો જરૂરી છે. Historical agreement records અને evidence ને ચૂપચાપ overwrite કરી શકાય નહીં.',evidence:'Operational statuses, timestamps, messages, collection અને delivery evidence, photographs, signatures, POD, invoices, payment records અને disputes service ચલાવવા અને audit trail રાખવા booking સાથે સાચવી શકાય છે.',law:'આ business terms England and Wales ના law હેઠળ governed છે. Business users માટે England and Wales ની courts પાસે exclusive jurisdiction છે, સિવાય જ્યાં કોઈ mandatory rule અન્ય રીતે લાગુ પડે.'},
    headings:{business:'વ્યવસાયિક સ્થિતિ અને અધિકાર',platform:'XDrive ની ભૂમિકા',booking:'Booking અને contract',payment:'Payment જવાબદારી',changes:'બદલાવ અને adjustments',evidence:'Evidence અને audit trail',law:'કાયદો અને jurisdiction'},
    membershipHeadings:['Eligibility અને access','Free અને paid periods','Renewal અને cancellation','Transport fees'],
    membershipBody:['Membership access અને eligibility XDrive માં દર્શાવેલા plan, onboarding અને compliance requirements હેઠળ છે.','કોઈપણ free access period promotional છે અને તેની cash value નથી. Paid membership ફક્ત disclosed plan અને billing arrangement અનુસાર શરૂ થાય છે.','Paid membership disclosed cycle અનુસાર cancellation સુધી renew થઈ શકે છે. Cancellation future renewals રોકે છે, પરંતુ સામાન્ય રીતે શરૂ થયેલ billing period reverse કરતી નથી, જો law અથવા XDrive અન્યથા જરૂરી ન કરે.','વર્તમાન membership model માં XDrive transport value પર percentage commission લેતું નથી, જો અલગ written product સ્પષ્ટ રીતે રજૂ ન થાય.'],
    privacyHeadings:['અમે કયો data process કરીએ છીએ','Transport-operation data','Sharing અને disclosures','Retention અને rights'],
    privacyBodies:['XDrive accounts બનાવવા, સુરક્ષિત રાખવા અને service આપવા identity, contact, company, device અને security data process કરે છે.','Transport operations માં collection અને delivery contacts, locations, messages, photographs, signatures, POD અને અન્ય evidence સામેલ હોઈ શકે છે. Users ફક્ત lawful, accurate અને booking માટે relevant personal data આપે.','Service ચલાવવા, users નું રક્ષણ કરવા અથવા law નું પાલન કરવા XDrive જરૂરી data authorised booking participants, service providers અને authorities સાથે share કરી શકે છે.','Retention record ના પ્રકાર, contractual અને legal obligations, dispute needs અને security requirements પર આધારિત છે. Rights requests public Privacy Policy ના contact details દ્વારા કરી શકાય છે.'],
    commercialHeadings:{paymentAck:'દરેક Award પર payment acknowledgement',buyerRisk:'Transport buyer risk અને exposure controls',amendmentsExtras:'Amendments અને approved extras',collectionEvidence:'Collection અને delivery evidence',brokerRole:'Broker role અને carrier-facing obligations',carrierCompliance:'Carrier compliance',subcontracting:'Subcontracting અને onward performance'},
    commercial:{paymentAck:'જ્યારે પણ transport buyer quote ને Award કરે છે, XDrive authorised user પાસે confirm કરાવે છે કે buyer transport service order કરે છે અને accepted booking terms તથા due date અનુસાર awarded carrier ને pay કરવા જવાબદાર છે. આ acknowledgement acting user, time અને applicable terms version સાથે record થાય છે.',buyerRisk:'Business transport buyer તરીકે કામ કરે ત્યારે XDrive Publish અને Award પર risk controls લાગુ કરી શકે છે. New buyer default restricted mode માં હોઈ શકે છે, વધુમાં વધુ 3 active transport commitments અને £2,500 outstanding transport exposure સાથે, જ્યાં સુધી authorised Platform Owner review અથવા override ન કરે.',amendmentsExtras:'Material commercial change અથવા additional charge original agreement overwrite કરી શકતું નથી. જ્યાં counterparty approval જરૂરી છે ત્યાં proposed amendment required acceptance પછી જ effective થાય છે. Approved waiting time, handball, redelivery, additional stops અને અન્ય extras traceable adjustments તરીકે retained રહે છે.',collectionEvidence:'XDrive booking આગળ વધે તે પહેલાં verified collection અને delivery evidence માગી શકે છે. Job ને Loaded mark કરતા પહેલાં verified collection handover અને ઓછામાં ઓછો એક collection photo, વધુમાં વધુ 10 photos સુધી, જરૂરી હોઈ શકે છે. Evidence actual booking સાથે સંબંધિત હોવું જોઈએ અને fabricated, reused અથવા misleading રીતે altered ન હોવું જોઈએ.',brokerRole:'Broker એ પોતાનો commercial role ચોક્કસ disclose કરવો જોઈએ અને અલગ customer arrangement ને એવી રીતે રજૂ ન કરવું જોઈએ કે carrier-facing agreement બદલાઈ ગયો હોય. જ્યાં broker transport buyer અથવા ordering party છે ત્યાં તે recorded carrier payment obligation માટે જવાબદાર રહે છે.',carrierCompliance:'Performing carrier suitable lawful vehicles અને personnel નો ઉપયોગ તથા required licences, insurance, permissions અને compliance documents જાળવવા માટે જવાબદાર છે. Booking accept કરવાથી આ obligations દૂર થતા નથી.',subcontracting:'જ્યાં subcontracting allowed હોય ત્યાં તેને arrange કરનાર party કામ કોણ કરશે તે વિશે ખોટી માહિતી આપી શકતી નથી અને disclosure, insurance તથા legal requirementsનું પાલન કરવું પડે છે. Explicit agreement વગર subcontracting existing contractual obligation transfer અથવા extinguish કરતી નથી.'}
  }
};

export const buildSupplementalControlledLegalDocument = (
  code: SupplementalControlledLegalDocumentCode,
  language: SupplementalLegalLanguage,
  version: string,
  privacyVersion: string,
) => {
  const pack = packs[language];
  const effectiveVersion = code === 'privacy_policy' ? privacyVersion : version;
  let sections: Array<{title:string;body:string}>;
  if (code === 'membership_subscription_terms') {
    sections = pack.membershipBody.map((body,index)=>({title:`${index + 1}. ${pack.membershipHeadings[index]}`,body}));
  } else if (code === 'privacy_policy') {
    sections = pack.privacyBodies.map((body,index)=>({title:`${index + 1}. ${pack.privacyHeadings[index]}`,body}));
  } else {
    const h=pack.headings;
    const s=pack.shared;
    sections=[
      {title:`1. ${h.business}`,body:s.business},
      {title:`2. ${h.platform}`,body:s.platformRole},
      {title:`3. ${h.booking}`,body:s.booking},
      {title:`4. ${h.payment}`,body:s.payment},
      {title:`5. ${h.changes}`,body:s.amendments},
      {title:`6. ${h.evidence}`,body:s.evidence},
      {title:`7. ${h.law}`,body:s.law},
    ];
    const c=pack.commercial;
    const ch=pack.commercialHeadings;
    if(code==='marketplace_transport_terms') sections.push({title:`8. ${ch.paymentAck}`,body:c.paymentAck},{title:`9. ${ch.buyerRisk}`,body:c.buyerRisk},{title:`10. ${ch.amendmentsExtras}`,body:c.amendmentsExtras},{title:`11. ${ch.collectionEvidence}`,body:c.collectionEvidence});
    else if(code==='customer_shipper_terms') sections.push({title:`8. ${ch.paymentAck}`,body:c.paymentAck},{title:`9. ${ch.buyerRisk}`,body:c.buyerRisk});
    else if(code==='broker_terms') sections.push({title:`8. ${ch.brokerRole}`,body:c.brokerRole},{title:`9. ${ch.paymentAck}`,body:c.paymentAck},{title:`10. ${ch.buyerRisk}`,body:c.buyerRisk});
    else if(code==='owner_driver_terms') sections.push({title:`8. ${ch.carrierCompliance}`,body:c.carrierCompliance},{title:`9. ${ch.collectionEvidence}`,body:c.collectionEvidence},{title:`10. ${ch.amendmentsExtras}`,body:c.amendmentsExtras});
    else if(code==='carrier_fleet_terms') sections.push({title:`8. ${ch.carrierCompliance}`,body:c.carrierCompliance},{title:`9. ${ch.subcontracting}`,body:c.subcontracting},{title:`10. ${ch.collectionEvidence}`,body:c.collectionEvidence},{title:`11. ${ch.amendmentsExtras}`,body:c.amendmentsExtras},{title:`12. ${ch.buyerRisk}`,body:c.buyerRisk});
  }
  return {code,language,canonicalLanguage:'en' as const,version:effectiveVersion,translationVersion:`${effectiveVersion}-${language}-1`,title:pack.titles[code],intro:pack.intro,sections};
};
