'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../components/AuthContext';
import { supabase } from '../../lib/supabaseClient';
import { useCompanyWorkspaceData } from '../components/workspace/useCompanyWorkspaceData';
import { ActionButton, DataTable, EmptyState, KpiCard, KpiGrid, PageFrame, PageHeader, Panel, StatusBadge } from '../components/workspace/WorkspaceUI';

const when=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'Not set';
const money=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
const active=new Set(['awarded','allocated','accepted','on_my_way','on_my_way_to_pickup','on_site_pickup','loaded','collected','in_transit','on_my_way_to_delivery','on_site_delivery']);
const daysUntil=(v:string|null|undefined)=>v?Math.ceil((new Date(v).getTime()-Date.now())/86400000):null;

export function DriverAvailabilityPage(){const data=useCompanyWorkspaceData();const router=useRouter();return <PageFrame><PageHeader eyebrow="Fleet resources" title="Driver Availability" description="Current and future driver capacity, separated from the commercial load board."/><KpiGrid><KpiCard label="Available" value={data.drivers.filter(d=>d.availability_status==='available').length} tone="green"/><KpiCard label="Busy" value={data.drivers.filter(d=>d.availability_status==='busy').length} tone="purple"/><KpiCard label="Offline" value={data.drivers.filter(d=>!d.availability_status||d.availability_status==='offline').length} tone="navy"/></KpiGrid><Panel title="Driver availability register"><DataTable columns={['Driver','Phone','Account status','Availability','Action']} rows={data.drivers.map(d=>[<strong key="name">{d.display_name??d.email??'Driver'}</strong>,d.phone??'Not recorded',<StatusBadge key="account" value={d.status??'unknown'}/>,<StatusBadge key="availability" value={d.availability_status??'offline'} tone={d.availability_status==='available'?'green':d.availability_status==='busy'?'purple':'grey'}/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/admin/drivers?driver=${d.id}`)}>View</ActionButton>])} empty={<EmptyState title="No drivers in the company roster"/>}/></Panel></PageFrame>}

export function FleetPositionsPage(){const data=useCompanyWorkspaceData();const locations=data.locations;const latest=useMemo(()=>{const map=new Map<string,(typeof locations)[number]>();for(const l of locations)if(!map.has(l.driver_id))map.set(l.driver_id,l);return map},[locations]);return <PageFrame><PageHeader eyebrow="Fleet tracking" title="Live Positions" description="Latest driver position, active job and stale-location warnings. The map remains secondary to operational exceptions."/><Panel title="Position register"><DataTable columns={['Driver','Coordinates','Last update','Job','Status']} rows={data.drivers.map(d=>{const l=latest.get(d.id);const ts=l?.recorded_at??l?.updated_at;const stale=!ts||Date.now()-new Date(ts).getTime()>20*60000;return [d.display_name??d.email??'Driver',l?`${l.lat.toFixed(5)}, ${l.lng.toFixed(5)}`:'No location',when(ts),l?.job_id?.slice(0,8)??'—',<StatusBadge key="status" value={stale?'stale':'live'} tone={stale?'red':'green'}/>]})} empty={<EmptyState title="No drivers available for live tracking"/>}/></Panel></PageFrame>}

export function FleetAssignmentsPage(){const data=useCompanyWorkspaceData();const router=useRouter();const jobs=data.jobs.filter(j=>['posted','awarded'].includes(j.status)&&!j.assigned_driver_id);return <PageFrame><PageHeader eyebrow="Fleet allocation" title="Assignments" description="Match job, available driver and suitable vehicle. Final allocation uses the existing controlled Diary workflow." actions={<ActionButton tone="secondary" onClick={()=>router.push('/admin/diary')}>Open Diary</ActionButton>}/><KpiGrid><KpiCard label="Jobs awaiting allocation" value={jobs.length} tone="orange"/><KpiCard label="Available drivers" value={data.drivers.filter(d=>d.availability_status==='available').length} tone="green"/><KpiCard label="Unassigned vehicles" value={data.vehicles.filter(v=>!v.assigned_driver_id).length} tone="blue"/></KpiGrid><Panel title="Allocation queue"><DataTable columns={['Route','Pickup','Vehicle required','Available resources','Action']} rows={jobs.map(j=>[<strong key="route">{j.pickup_location} → {j.delivery_location}</strong>,when(j.pickup_datetime),(j.vehicle_type??'Not specified').replace(/_/g,' '),`${data.drivers.filter(d=>d.availability_status==='available').length} drivers · ${data.vehicles.length} vehicles`,<ActionButton key="action" tone="success" onClick={()=>router.push(`/admin/diary?job=${j.id}`)}>Allocate</ActionButton>])} empty={<EmptyState title="No jobs awaiting allocation"/>}/></Panel></PageFrame>}

export function FleetActiveJobsPage(){const data=useCompanyWorkspaceData();const router=useRouter();const jobs=data.jobs.filter(j=>active.has(j.current_status??j.status));return <PageFrame><PageHeader eyebrow="Fleet operations" title="Active Jobs" description="Live collections and deliveries with resource and delay visibility."/><Panel><DataTable columns={['Route','Pickup','Delivery','Driver','Vehicle','Status','Action']} rows={jobs.map(j=>[<strong key="route">{j.pickup_location} → {j.delivery_location}</strong>,when(j.pickup_datetime),when(j.delivery_datetime),j.assigned_driver_id?.slice(0,8)??'Not assigned',(j.vehicle_type??'Not specified').replace(/_/g,' '),<StatusBadge key="status" value={j.current_status??j.status}/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/admin/jobs?job=${j.id}`)}>Open</ActionButton>])} empty={<EmptyState title="No active jobs"/>}/></Panel></PageFrame>}

export function FleetMaintenancePage(){const data=useCompanyWorkspaceData();const router=useRouter();return <PageFrame><PageHeader eyebrow="Vehicle readiness" title="Maintenance" description="Vehicle readiness, defects, service work and off-road decisions belong in the Fleet workspace."/><KpiGrid><KpiCard label="Fleet vehicles" value={data.vehicles.length}/><KpiCard label="Without assigned driver" value={data.vehicles.filter(v=>!v.assigned_driver_id).length} tone="orange"/><KpiCard label="Vehicle documents expiring" value={data.vehicleDocuments.filter(d=>{const days=daysUntil(d.expiry_date);return days!==null&&days<=30}).length} tone="red"/></KpiGrid><Panel title="Vehicle maintenance register"><DataTable columns={['Registration','Vehicle','Assigned driver','Readiness','Next action']} rows={data.vehicles.map(v=>[<strong key="reg">{v.reg_plate??'No registration'}</strong>,`${v.make??''} ${v.model??''}`.trim()||v.type?.replace(/_/g,' ')||'Vehicle',v.assigned_driver_id?.slice(0,8)??'Not assigned',<StatusBadge key="status" value="Operational" tone="green"/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/admin/vehicles?vehicle=${v.id}`)}>Open vehicle</ActionButton>])} empty={<EmptyState title="No vehicles in the fleet"/>}/></Panel></PageFrame>}

export function FutureAvailabilityPage(){const router=useRouter();return <PageFrame><PageHeader eyebrow="Capacity planning" title="Future Availability" description="Return journeys, future driver positions, planned leave and pre-booked capacity." actions={<ActionButton tone="secondary" onClick={()=>router.push('/admin/returns')}>Return Journeys</ActionButton>}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:'0.9rem'}}>{['Return journeys','Future driver positions','Planned leave','Pre-booked jobs'].map(title=><Panel key={title} title={title}><EmptyState title={`No ${title.toLowerCase()} recorded`}/></Panel>)}</div></PageFrame>}

export function DocumentExpiryPage(){const data=useCompanyWorkspaceData();const docs=data.driverDocuments.concat(data.vehicleDocuments).filter(d=>d.expiry_date).sort((a,b)=>new Date(a.expiry_date??0).getTime()-new Date(b.expiry_date??0).getTime());return <PageFrame><PageHeader eyebrow="Compliance calendar" title="Document Expiry" description="Expired and expiring driver and vehicle evidence, ordered by urgency."/><KpiGrid><KpiCard label="Expired" value={docs.filter(d=>(daysUntil(d.expiry_date)??1)<0).length} tone="red"/><KpiCard label="Due in 7 days" value={docs.filter(d=>{const x=daysUntil(d.expiry_date);return x!==null&&x>=0&&x<=7}).length} tone="orange"/><KpiCard label="Due in 30 days" value={docs.filter(d=>{const x=daysUntil(d.expiry_date);return x!==null&&x>7&&x<=30}).length} tone="blue"/></KpiGrid><Panel><DataTable columns={['Document','Entity','Expiry','Days remaining','Verification']} rows={docs.map(d=>[d.doc_type?.replace(/_/g,' ')??'Document',d.driver_id?'Driver':'Vehicle',new Date(d.expiry_date??'').toLocaleDateString('en-GB'),daysUntil(d.expiry_date),<StatusBadge key="status" value={d.status??'pending'}/>])} empty={<EmptyState title="No expiry dates recorded"/>}/></Panel></PageFrame>}

export function IncidentsPage(){const router=useRouter();return <PageFrame><PageHeader eyebrow="Operational exceptions" title="Incidents" description="Accidents, breakdowns, failed deliveries, cargo damage and complaints require a controlled incident record." actions={<ActionButton tone="secondary" onClick={()=>router.push('/admin/disputes')}>Open Disputes</ActionButton>}/><Panel><EmptyState title="No incident register entries" description="Existing dispute cases remain available in the Disputes module; the consolidated incident register is ready for structured records."/></Panel></PageFrame>}

export function FinancePaymentsPage(){const data=useCompanyWorkspaceData();return <PageFrame><PageHeader eyebrow="Finance" title="Payments" description="Payment reconciliation is separated from invoice issuance and operational job status."/><Panel><DataTable columns={['Invoice','Counterparty','Amount','Payment status','Due']} rows={data.invoices.map(i=>[i.invoice_number??i.id.slice(0,8),i.client_name??'Counterparty',money(Number(i.amount??0)),<StatusBadge key="status" value={i.payment_status??i.status}/>,i.due_date?new Date(i.due_date).toLocaleDateString('en-GB'):'Not set'])} empty={<EmptyState title="No payment records"/>}/></Panel></PageFrame>}
export function FinanceBalancesPage(){const data=useCompanyWorkspaceData();const unpaid=data.invoices.filter(i=>i.payment_status!=='paid'&&!['paid','Paid'].includes(i.status));return <PageFrame><PageHeader eyebrow="Finance" title="Outstanding Balances" description="Amounts owed by customers and amounts payable to carriers."/><KpiGrid><KpiCard label="Outstanding invoices" value={unpaid.length} tone="orange"/><KpiCard label="Outstanding value" value={money(unpaid.reduce((s,i)=>s+Number(i.amount??0),0))} tone="navy"/></KpiGrid><Panel><DataTable columns={['Invoice','Counterparty','Amount','Due','Status']} rows={unpaid.map(i=>[i.invoice_number??i.id.slice(0,8),i.client_name??'Counterparty',money(Number(i.amount??0)),i.due_date?new Date(i.due_date).toLocaleDateString('en-GB'):'Not set',<StatusBadge key="status" value={i.payment_status??i.status}/>])}/></Panel></PageFrame>}
export function FinanceReportsPage(){return <PageFrame><PageHeader eyebrow="Finance" title="Reports & Exports" description="VAT, invoice, payment and balance exports are isolated from operations."/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:'0.9rem'}}>{['Invoice register','Payment reconciliation','Outstanding balances','VAT summary','Job profitability'].map(title=><Panel key={title} title={title}><p style={{margin:0,color:'#64748b',fontSize:'0.78rem'}}>Report scope: current company only.</p></Panel>)}</div></PageFrame>}

export function NotificationsPage(){const {user}=useAuth();const [rows,setRows]=useState<Array<{id:string;event_type:string;entity_type:string;status:string;created_at:string}>>([]);useEffect(()=>{if(!user?.id)return;supabase.from('notification_events').select('id,event_type,entity_type,status,created_at').eq('recipient_user_id',user.id).order('created_at',{ascending:false}).limit(100).then(({data})=>setRows((data??[]) as typeof rows));},[user?.id]);return <PageFrame><PageHeader eyebrow="Workspace notifications" title="Notifications" description="Operational and commercial events addressed to the current user."/><Panel><DataTable columns={['Event','Entity','Time','Delivery status']} rows={rows.map(r=>[r.event_type.replace(/_/g,' '),r.entity_type,when(r.created_at),<StatusBadge key="status" value={r.status}/>])} empty={<EmptyState title="No notifications"/>}/></Panel></PageFrame>}
