'use client';

import { useCallback, useEffect, useState } from 'react';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import { PlatformEntityLink } from '@/app/super-admin/_components/control-plane';
import { getAuthHeader } from '@/app/super-admin/_lib/getAuthHeader';

const THEME = { pageBg:'#F4F6F8', cardBg:'#FFFFFF', cardBorder:'#D9E1EA', text:'#1A1F2B', heading:'#0B2F6B', blue:'#1D57D8', muted:'#64748B', accent:'#F5A300', green:'#16A34A', red:'#DC2626' } as const;
type Company = { id:string; name:string; company_number:string|null; email:string|null; status:string; company_type:string|null; created_at:string };
type PendingReinstate = { companyId:string; companyName:string } | null;

function ReinstateModal({ pending, onConfirm, onCancel, submitting }: { pending:PendingReinstate; onConfirm:(reason:string)=>void; onCancel:()=>void; submitting:boolean }) {
  const [reason,setReason]=useState('');
  useEffect(()=>{ setReason(''); },[pending?.companyId]);
  if(!pending)return null;
  return <div style={{position:'fixed',inset:0,zIndex:1000,backgroundColor:'rgba(26,31,43,0.56)',display:'flex',alignItems:'center',justifyContent:'center',padding:'16px'}} onClick={(event)=>{if(event.target===event.currentTarget)onCancel();}}>
    <div role="dialog" aria-modal="true" style={{backgroundColor:THEME.cardBg,border:`1px solid ${THEME.cardBorder}`,borderRadius:'4px',padding:'16px',width:'100%',maxWidth:'420px',boxShadow:'0 14px 34px rgba(11,47,107,.16)'}}>
      <h2 style={{margin:'0 0 5px',fontSize:'16px',fontWeight:800,color:THEME.heading}}>Reinstate company</h2>
      <p style={{margin:'0 0 12px',fontSize:'12px',color:THEME.muted,lineHeight:1.45}}>Reinstate <strong style={{color:THEME.text}}>{pending.companyName}</strong> and restore platform access through the canonical company-governance action.</p>
      <label style={{display:'block',marginBottom:'5px',fontSize:'11px',fontWeight:700,color:THEME.heading}}>Reason / notes</label>
      <textarea value={reason} onChange={(event)=>setReason(event.target.value)} rows={3} placeholder="Record why this company is being reinstated…" style={{width:'100%',boxSizing:'border-box',backgroundColor:'#FFFFFF',border:`1px solid ${THEME.cardBorder}`,borderRadius:'4px',padding:'8px 10px',color:THEME.text,fontSize:'12px',resize:'vertical',outlineColor:THEME.blue}} />
      <div style={{display:'flex',gap:'6px',marginTop:'12px',justifyContent:'flex-end'}}><button onClick={onCancel} disabled={submitting} style={modalButton(false,submitting)}>Cancel</button><button onClick={()=>onConfirm(reason.trim())} disabled={submitting} style={modalButton(true,submitting)}>{submitting?'Working…':'Confirm Reinstatement'}</button></div>
    </div>
  </div>;
}

function SuspendedContent(){
  const [companies,setCompanies]=useState<Company[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [pending,setPending]=useState<PendingReinstate>(null); const [submitting,setSubmitting]=useState(false); const [actionMessage,setActionMessage]=useState<string|null>(null);
  const fetchSuspended=useCallback(async()=>{setLoading(true);setError(null);setCompanies([]);try{const auth=await getAuthHeader();if(!auth){setError('No active Platform Owner session.');return;}const response=await fetch('/api/super-admin/companies?status=suspended',{headers:{Authorization:auth},cache:'no-store'});const body=await response.json().catch(()=>({})) as {companies?:Company[];error?:string};if(!response.ok){setError(body.error??'Company service is currently unavailable.');return;}setCompanies(body.companies??[]);}catch{setError('Company service is currently unavailable.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void fetchSuspended();},[fetchSuspended]);
  const handleConfirm=async(reason:string)=>{if(!pending)return;setSubmitting(true);setActionMessage(null);try{const auth=await getAuthHeader();if(!auth){setActionMessage('No active Platform Owner session.');return;}const body:Record<string,string>={action:'reinstate'};if(reason)body.reason=reason;const response=await fetch(`/api/super-admin/companies/${pending.companyId}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:auth},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({})) as {error?:string};if(!response.ok){setActionMessage(payload.error??'The company could not be reinstated.');}else{setActionMessage('Company reinstated successfully.');await fetchSuspended();}}catch{setActionMessage('The company could not be reinstated.');}finally{setPending(null);setSubmitting(false);}};
  const fmt=(iso:string)=>new Date(iso).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
  return <><ReinstateModal pending={pending} onConfirm={handleConfirm} onCancel={()=>setPending(null)} submitting={submitting}/><div style={{minHeight:'100vh',backgroundColor:THEME.pageBg,color:THEME.text,padding:'12px'}}>
    <header style={{minHeight:'52px',display:'flex',alignItems:'center',gap:'10px',marginBottom:'12px',flexWrap:'wrap'}}><span aria-hidden="true" style={{width:'28px',height:'28px',display:'grid',placeItems:'center',borderRadius:'4px',background:THEME.heading,color:'#FFFFFF',fontSize:'12px'}}>×</span><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:'8px',flexWrap:'wrap'}}><h1 style={{fontSize:'20px',fontWeight:800,color:THEME.heading,margin:0}}>Suspended Companies</h1><span style={{fontSize:'10px',fontWeight:800,textTransform:'uppercase',color:THEME.blue,backgroundColor:'#EEF4FF',padding:'3px 6px',borderRadius:'4px'}}>Companies</span><span style={{fontSize:'10px',color:THEME.muted}}>{loading?'…':error?'— total':`${companies.length} total`}</span></div><p style={{color:THEME.muted,margin:'4px 0 0',fontSize:'12px'}}>Suspended companies. Inspect authoritative context before reinstating platform access.</p></div><button onClick={()=>void fetchSuspended()} disabled={loading} style={{height:'32px',padding:'0 10px',borderRadius:'4px',border:`1px solid ${THEME.blue}`,background:THEME.blue,color:'#FFFFFF',fontWeight:800,fontSize:'11px',cursor:loading?'not-allowed':'pointer',opacity:loading ? .65 : 1}}>{loading?'Loading…':'Refresh'}</button></header>
    {actionMessage&&<div style={{backgroundColor:THEME.cardBg,border:`1px solid ${THEME.accent}`,borderLeft:`4px solid ${THEME.accent}`,borderRadius:'4px',padding:'9px 12px',color:THEME.text,fontSize:'11px',marginBottom:'12px'}}>{actionMessage}</div>}{error&&<div role="alert" style={{backgroundColor:THEME.cardBg,border:`1px solid ${THEME.red}`,borderLeft:`4px solid ${THEME.red}`,borderRadius:'4px',padding:'9px 12px',color:THEME.red,fontSize:'11px',fontWeight:700,marginBottom:'12px'}}>{error}</div>}
    <section style={{backgroundColor:THEME.cardBg,border:`1px solid ${THEME.cardBorder}`,borderRadius:'4px',overflow:'hidden'}}>{loading?<div style={stateStyle}>Loading…</div>:error?<div style={stateStyle}>Suspended-company registry unavailable. No empty result is inferred.</div>:companies.length===0?<div style={stateStyle}>No suspended companies.</div>:<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:'920px',fontSize:'12px'}}><thead><tr style={{height:'38px',background:THEME.pageBg,borderBottom:`1px solid ${THEME.cardBorder}`}}>{['Company name','Reg. number','Email','Type','Created','Controls'].map((heading)=><th key={heading} style={{padding:'0 12px',textAlign:'left',color:THEME.heading,fontWeight:800,fontSize:'10px',textTransform:'uppercase',letterSpacing:'0.04em',whiteSpace:'nowrap'}}>{heading}</th>)}</tr></thead><tbody>{companies.map((company)=><tr key={company.id} style={{borderBottom:`1px solid ${THEME.cardBorder}`}}><td style={{padding:'9px 12px',color:THEME.text,fontWeight:700}}>{company.name}<span style={{marginLeft:'6px',fontSize:'10px',color:THEME.red,backgroundColor:'#FEF2F2',border:'1px solid #FECACA',borderRadius:'4px',padding:'2px 5px',fontWeight:800,textTransform:'uppercase'}}>Suspended</span></td><td style={cell}>{company.company_number??'—'}</td><td style={cell}>{company.email??'—'}</td><td style={cell}>{company.company_type??'standard'}</td><td style={cell}>{fmt(company.created_at)}</td><td style={{padding:'9px 12px'}}><div style={{display:'flex',gap:'6px',alignItems:'center',flexWrap:'wrap'}}><PlatformEntityLink entityType="company" entityId={company.id} compact>Inspect</PlatformEntityLink><button onClick={()=>{setActionMessage(null);setPending({companyId:company.id,companyName:company.name});}} disabled={submitting&&pending?.companyId===company.id} style={{height:'30px',padding:'0 9px',borderRadius:'4px',border:`1px solid ${THEME.green}`,backgroundColor:'#FFFFFF',color:THEME.green,fontWeight:800,fontSize:'10px',cursor:'pointer'}}>Reinstate</button></div></td></tr>)}</tbody></table></div>}</section>
  </div></>;
}

const stateStyle={padding:'18px',textAlign:'center' as const,color:THEME.muted,fontSize:'12px'};
const cell={padding:'9px 12px',color:THEME.muted} as const;
const modalButton=(primary:boolean,disabled:boolean)=>({height:'32px',padding:'0 10px',borderRadius:'4px',border:`1px solid ${primary?THEME.green:THEME.cardBorder}`,backgroundColor:primary?THEME.green:'#FFFFFF',color:primary?'#FFFFFF':THEME.heading,fontSize:'11px',fontWeight:800,cursor:disabled?'not-allowed':'pointer',opacity:disabled ? .6 : 1} as const);
export default function Page(){return <ProtectedRoute allowedRoles={['owner']}><SuspendedContent/></ProtectedRoute>;}
