'use client';

import { useCallback, useEffect, useState } from 'react';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import { getAuthHeader } from '@/app/super-admin/_lib/getAuthHeader';

const X={navy:'#0B2F6B',blue:'#1D57D8',orange:'#F5A300',white:'#FFFFFF',charcoal:'#1A1F2B',light:'#F4F6F8',border:'#D9E1EA',muted:'#64748B',green:'#16A34A',red:'#DC2626'} as const;
type UserRow={id:string;user_id:string;name:string;email:string;status?:string;role:string;company?:string;company_id?:string|null;availability_status?:string;app_access?:boolean;phone?:string;created_at:string;};
type ApiResponse={rows:UserRow[];total:number;totalDrivers?:number;roleCounts?:Record<string,number>;};
const fmt=(iso:string|null|undefined)=>iso?new Date(iso).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
const statusDot=(status:string|undefined)=>{const s=(status??'').toLowerCase();const color=s==='active'||s==='available'?X.green:s==='suspended'||s==='inactive'||s==='busy'?X.red:X.muted;return <span style={{display:'inline-flex',alignItems:'center',gap:'5px',fontSize:'11px',color,fontWeight:700}}><span style={{width:7,height:7,borderRadius:'50%',backgroundColor:color,display:'inline-block'}}/>{s||'—'}</span>;};
type SuperAdminUserListPageProps={icon:string;title:string;description:string;section:string;roleFilter:string;columns:Array<{label:string;render:(row:UserRow)=>React.ReactNode;}>;};

export default function SuperAdminUserListPage({icon,title,description,section,roleFilter,columns}:SuperAdminUserListPageProps){
 const[rows,setRows]=useState<UserRow[]>([]);const[total,setTotal]=useState(0);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[search,setSearch]=useState('');
 const fetchUsers=useCallback(async()=>{setLoading(true);setError(null);setRows([]);setTotal(0);try{const auth=await getAuthHeader();if(!auth){setError('No active session.');return;}const url=roleFilter?`/api/super-admin/users?role=${encodeURIComponent(roleFilter)}&limit=500`:'/api/super-admin/users?limit=500';const res=await fetch(url,{headers:{Authorization:auth}});const body=await res.json().catch(()=>({}));if(!res.ok){setError((body as {error?:string}).error??'User service is currently unavailable.');return;}const data=body as ApiResponse;if(!Array.isArray(data.rows)||typeof data.total!=='number'){setError('User service returned an invalid response.');return;}setRows(data.rows);setTotal(data.total);}catch{setError('User service is currently unavailable.');}finally{setLoading(false);}},[roleFilter]);
 useEffect(()=>{void fetchUsers();},[fetchUsers]);
 const filtered=search.trim()?rows.filter(row=>[row.name,row.email,row.company??'',row.role].some(f=>f.toLowerCase().includes(search.toLowerCase()))):rows;
 return <ProtectedRoute allowedRoles={['owner']}><div style={{minHeight:'100vh',background:X.light,color:X.charcoal,padding:'12px'}}>
  <header style={{minHeight:'52px',display:'flex',alignItems:'center',gap:'10px',marginBottom:'12px'}}><span aria-hidden='true' style={{width:'28px',height:'28px',display:'grid',placeItems:'center',borderRadius:'4px',background:X.navy,color:X.white,fontSize:'12px'}}>{icon}</span><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:'8px',flexWrap:'wrap'}}><h1 style={{margin:0,color:X.navy,fontSize:'20px',fontWeight:800}}>{title}</h1><span style={{padding:'3px 6px',borderRadius:'4px',background:'#EEF4FF',color:X.blue,fontSize:'10px',fontWeight:800,textTransform:'uppercase'}}>{section}</span><span style={{fontSize:'10px',color:X.muted}}>{loading?'…':error?'Unavailable':`${total} total`}</span></div><p style={{margin:'4px 0 0',color:X.muted,fontSize:'12px'}}>{description}</p></div><button onClick={()=>void fetchUsers()} disabled={loading} style={{height:'32px',padding:'0 10px',background:X.blue,color:X.white,border:`1px solid ${X.blue}`,borderRadius:'4px',fontWeight:800,fontSize:'11px',cursor:loading?'not-allowed':'pointer',opacity:loading?.65:1}}>{loading?'Loading…':'Refresh'}</button></header>
  {error&&<div role='alert' style={{marginBottom:'12px',border:`1px solid ${X.red}`,borderLeft:`4px solid ${X.red}`,borderRadius:'4px',background:X.white,padding:'9px 12px',color:X.red,fontSize:'11px',fontWeight:700}}>{error}</div>}
  {!error&&<><div style={{minHeight:'40px',display:'flex',alignItems:'center',gap:'8px',marginBottom:'12px'}}><input type='text' value={search} onChange={e=>setSearch(e.target.value)} placeholder='Filter by name, email or company…' style={{width:'100%',maxWidth:'360px',height:'32px',border:`1px solid ${X.border}`,borderRadius:'4px',padding:'0 8px',background:X.white,color:X.charcoal,fontSize:'12px',boxSizing:'border-box',outlineColor:X.blue}}/></div>
  <section style={{background:X.white,border:`1px solid ${X.border}`,borderRadius:'4px',overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'12px'}}><thead><tr style={{height:'38px',background:X.light,borderBottom:`1px solid ${X.border}`}}>{columns.map(col=><th key={col.label} style={{padding:'0 12px',textAlign:'left',color:X.navy,fontWeight:800,textTransform:'uppercase',letterSpacing:'.04em',fontSize:'10px',whiteSpace:'nowrap'}}>{col.label}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={columns.length} style={{padding:'18px',textAlign:'center',color:X.muted}}>Loading {title.toLowerCase()}…</td></tr>:filtered.length===0?<tr><td colSpan={columns.length} style={{padding:'18px',textAlign:'center',color:X.muted}}>{search?'No results match the filter.':`No ${title.toLowerCase()} found.`}</td></tr>:filtered.map(row=><tr key={row.id} style={{minHeight:'44px',borderBottom:`1px solid ${X.border}`}}>{columns.map(col=><td key={col.label} style={{padding:'9px 12px',color:X.charcoal,verticalAlign:'middle'}}>{col.render(row)}</td>)}</tr>)}</tbody></table></div></section>
  {filtered.length>0&&<div style={{marginTop:'6px',color:X.muted,fontSize:'10px'}}>Showing {filtered.length} of {total} records{search?` (filtered from ${rows.length})`:''}.</div>}</>}</div></ProtectedRoute>;
}
export{statusDot,fmt};
