'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { supabase } from '../../../lib/supabaseClient';
import PodDocumentsPage from '../../components/workspace/PodDocumentsPage';
import { useCompanyWorkspaceData, type WorkspaceDocument, type WorkspaceDriver, type WorkspaceJob, type WorkspaceVehicle } from '../../components/workspace/useCompanyWorkspaceData';
import { ActionButton, AlertBanner, DataTable, EmptyState, KpiCard, KpiGrid, PageFrame, PageHeader, Panel, ProgressSteps, StatusBadge, TwoColumn, workspaceTheme } from '../../components/workspace/WorkspaceUI';

const lifecycle = ['awarded','allocated','accepted','on_my_way_to_pickup','on_site_pickup','loaded','on_my_way_to_delivery','on_site_delivery','delivered'];
const activeStages = new Set(['accepted','on_my_way','on_my_way_to_pickup','on_site_pickup','loaded','collected','in_transit','on_my_way_to_delivery','on_site_delivery']);
const exceptionStages = new Set(['delayed','incident','waiting_time','cancelled','failed','delivery_failed','collection_failed','disputed','exception','breakdown']);
const terminalStages = new Set(['delivered','completed','cancelled','paid']);
const norm = (value: string | null | undefined) => (value ?? '').trim().toLowerCase();
export const statusOf = (job: WorkspaceJob) => norm(job.current_status ?? job.status);
export const label = (value: string | null | undefined) => (value || 'unknown').replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
export const when = (value: string | null | undefined) => value ? new Date(value).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}) : 'Not set';
const route = (job: WorkspaceJob) => `${job.pickup_postcode ?? job.pickup_location ?? 'Collection'} → ${job.delivery_postcode ?? job.delivery_location ?? 'Delivery'}`;
const daysUntil = (value: string | null | undefined) => value ? Math.ceil((new Date(value).getTime()-Date.now())/86400000) : null;
const isExpired = (document: WorkspaceDocument) => { const days=daysUntil(document.expiry_date); return days!==null && days<0; };
const isExpiring = (document: WorkspaceDocument) => { const days=daysUntil(document.expiry_date); return days!==null && days>=0 && days<=30; };
const isRejected = (document: WorkspaceDocument) => ['rejected','invalid','failed'].includes(norm(document.status));
const currentDocs = (documents: WorkspaceDocument[]) => documents.length>0 && documents.every((document)=>!isExpired(document)&&!isRejected(document));
const driverDocs = (driver: WorkspaceDriver, documents: WorkspaceDocument[]) => documents.filter((document)=>document.driver_id===driver.id);
const vehicleDocs = (vehicle: WorkspaceVehicle, documents: WorkspaceDocument[]) => documents.filter((document)=>document.vehicle_id===vehicle.id);
const driverActive = (driver: WorkspaceDriver) => !['inactive','suspended','disabled','rejected'].includes(norm(driver.status));
const driverAssignedJob = (driver: WorkspaceDriver,jobs:WorkspaceJob[]) => jobs.find((job)=>job.assigned_driver_id===driver.id && !terminalStages.has(statusOf(job)));
export const driverReady = (driver: WorkspaceDriver,jobs:WorkspaceJob[],documents:WorkspaceDocument[]) => driverActive(driver) && norm(driver.availability_status)==='available' && !driverAssignedJob(driver,jobs) && currentDocs(driverDocs(driver,documents));
export const vehicleCompliance = (vehicle:WorkspaceVehicle,documents:WorkspaceDocument[]) => { const docs=vehicleDocs(vehicle,documents); if(docs.some(isExpired)) return 'expired'; if(docs.some(isRejected)) return 'non-compliant'; if(docs.some(isExpiring)) return 'expiring'; if(docs.length===0) return 'documents missing'; return 'current'; };
export const vehicleReady = (vehicle:WorkspaceVehicle,documents:WorkspaceDocument[]) => !vehicle.assigned_driver_id && vehicleCompliance(vehicle,documents)==='current';
const jobAwarded = (job:WorkspaceJob)=>statusOf(job)==='awarded' && !job.assigned_driver_id;
const jobAllocated = (job:WorkspaceJob)=>statusOf(job)==='allocated' || (Boolean(job.assigned_driver_id)&&['awarded','posted'].includes(statusOf(job)));
const jobActive = (job:WorkspaceJob)=>activeStages.has(statusOf(job));
const jobOverdue = (job:WorkspaceJob)=>Boolean(job.delivery_datetime && new Date(job.delivery_datetime).getTime()<Date.now() && !terminalStages.has(statusOf(job)));
const pickupRisk = (job:WorkspaceJob)=>Boolean(job.pickup_datetime && new Date(job.pickup_datetime).getTime()-Date.now()<2*60*60*1000 && new Date(job.pickup_datetime).getTime()>Date.now() && !job.assigned_driver_id);
const invoiceState=(invoice:{payment_status?:string|null;status:string;due_date?:string|null})=>norm(invoice.payment_status ?? invoice.status);
const invoiceOverdue=(invoice:{payment_status?:string|null;status:string;due_date?:string|null})=>invoiceState(invoice)!=='paid'&&Boolean(invoice.due_date&&new Date(invoice.due_date).getTime()<Date.now());
const latestLocation=(driverId:string,locations:ReturnType<typeof useCompanyWorkspaceData>['locations'])=>locations.find((location)=>location.driver_id===driverId);

export function FleetDashboardView(){
 const router=useRouter(); const data=useCompanyWorkspaceData();
 const metrics=useMemo(()=>{
  const availableDrivers=data.drivers.filter((driver)=>driverReady(driver,data.jobs,data.driverDocuments)).length;
  const unavailableDrivers=data.drivers.length-availableDrivers;
  const readyVehicles=data.vehicles.filter((vehicle)=>vehicleReady(vehicle,data.vehicleDocuments)).length;
  const vehicleIssues=data.vehicles.filter((vehicle)=>vehicleCompliance(vehicle,data.vehicleDocuments)!=='current').length;
  const awarded=data.jobs.filter(jobAwarded).length; const allocated=data.jobs.filter(jobAllocated).length;
  const active=data.jobs.filter(jobActive).length; const delayed=data.jobs.filter((job)=>jobOverdue(job)||exceptionStages.has(statusOf(job))).length;
  const missingPod=data.jobs.filter((job)=>['delivered','completed'].includes(statusOf(job))&&(job.delivery_photos?.length??0)===0).length;
  const compliance=data.driverDocuments.concat(data.vehicleDocuments).filter((document)=>isExpired(document)||isExpiring(document)||isRejected(document)).length;
  const unpaid=data.invoices.filter((invoice)=>invoiceState(invoice)!=='paid').length; const overdue=data.invoices.filter(invoiceOverdue).length;
  return {availableDrivers,unavailableDrivers,readyVehicles,vehicleIssues,awarded,allocated,active,delayed,missingPod,compliance,unpaid,overdue};
 },[data]);
 const attention=data.jobs.filter((job)=>jobAwarded(job)||jobAllocated(job)||pickupRisk(job)||jobOverdue(job)||exceptionStages.has(statusOf(job))||(['delivered','completed'].includes(statusOf(job))&&(job.delivery_photos?.length??0)===0));
 return <PageFrame><PageHeader eyebrow="Fleet operations" title="Fleet Dashboard" description="Company-scoped capacity, allocation, active transport, compliance, POD and finance exceptions from persisted operational records." actions={<><ActionButton tone="success" onClick={()=>router.push('/admin/fleet/assignments')}>Allocate Work</ActionButton><ActionButton tone="secondary" onClick={()=>router.push('/admin/fleet/positions')}>Live Positions</ActionButton></>}/>{data.error&&<AlertBanner>{data.error}</AlertBanner>}
 <KpiGrid><KpiCard label="Available drivers" value={metrics.availableDrivers} tone="green" detail="Active, explicitly available, unassigned and compliant"/><KpiCard label="Unavailable drivers" value={metrics.unavailableDrivers} tone="orange"/><KpiCard label="Allocation-ready vehicles" value={metrics.readyVehicles} tone="blue" detail="Unassigned with current documents"/><KpiCard label="Vehicle compliance issues" value={metrics.vehicleIssues} tone="red"/><KpiCard label="Awarded, unallocated" value={metrics.awarded} tone="orange"/><KpiCard label="Allocated, awaiting acceptance" value={metrics.allocated} tone="purple"/><KpiCard label="Active deliveries" value={metrics.active} tone="green"/><KpiCard label="Delayed / exceptions" value={metrics.delayed} tone="red"/><KpiCard label="Missing POD" value={metrics.missingPod} tone="orange"/><KpiCard label="Compliance alerts" value={metrics.compliance} tone="red"/><KpiCard label="Unpaid invoices" value={metrics.unpaid} tone="navy" detail={`${metrics.overdue} overdue`}/></KpiGrid>
 <TwoColumn><Panel title="Fleet attention queue" description="Only records requiring allocation, delay, exception or POD action." actions={<ActionButton tone="secondary" onClick={()=>router.push('/admin/jobs')}>All Jobs</ActionButton>}><DataTable columns={['Load','Route','Pickup','Issue','Lifecycle','Action']} rows={attention.slice(0,12).map((job)=>{let issue='Operational action'; if(jobAwarded(job)) issue='Awarded job not allocated'; else if(jobAllocated(job)) issue='Allocated, awaiting acceptance'; else if(pickupRisk(job)) issue='Pickup approaching without allocation'; else if(jobOverdue(job)) issue='Delivery ETA overdue'; else if(['delivered','completed'].includes(statusOf(job))&&(job.delivery_photos?.length??0)===0) issue='Missing POD'; else if(exceptionStages.has(statusOf(job))) issue=label(statusOf(job)); return [job.id.slice(0,8).toUpperCase(),<strong key="route">{route(job)}</strong>,when(job.pickup_datetime),issue,<StatusBadge key="status" value={label(statusOf(job))}/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(jobAwarded(job)||jobAllocated(job)?`/admin/fleet/assignments?job=${job.id}`:`/admin/jobs?job=${job.id}`)}>Open</ActionButton>];})} empty={<EmptyState title="No Fleet action required" description="Healthy and completed records are intentionally excluded."/>}/></Panel>
 <div style={{display:'grid',gap:'0.8rem'}}><Panel title="Quick actions"><div style={{display:'grid',gap:'0.5rem'}}>{[['Allocate jobs','/admin/fleet/assignments'],['Manage drivers','/admin/drivers'],['Manage vehicles','/admin/vehicles'],['Monitor deliveries','/admin/fleet/active-jobs'],['Review compliance','/admin/documents/expiry'],['Open finance','/admin/invoices'],['Notifications','/admin/notifications'],['Fleet Settings','/admin/settings']].map(([text,href])=><ActionButton key={href} tone="secondary" onClick={()=>router.push(href)}>{text}</ActionButton>)}</div></Panel><Panel title="Recent activity" description="Real job and invoice timestamps only."><DataTable columns={['Record','Event','Time']} rows={[...data.jobs.map((job)=>({id:job.id,event:`${label(statusOf(job))} · ${route(job)}`,at:job.updated_at})),...data.invoices.map((invoice)=>({id:invoice.id,event:`Invoice ${invoice.invoice_number??invoice.id.slice(0,8)} · ${label(invoiceState(invoice))}`,at:invoice.created_at}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()).slice(0,8).map((item)=>[item.id.slice(0,8).toUpperCase(),item.event,when(item.at)])} empty={<EmptyState title="No recent activity"/>}/></Panel></div></TwoColumn></PageFrame>;
}

export function FleetAssignmentsView(){
 const data=useCompanyWorkspaceData(); const router=useRouter(); const search=useSearchParams(); const selected=search.get('job');
 const jobs=data.jobs.filter((job)=>jobAwarded(job)||jobAllocated(job));
 const eligibleDrivers=data.drivers.filter((driver)=>driverReady(driver,data.jobs,data.driverDocuments));
 const eligibleVehicles=data.vehicles.filter((vehicle)=>vehicleReady(vehicle,data.vehicleDocuments));
 return <PageFrame><PageHeader eyebrow="Fleet allocation" title="Assignments" description="Existing diary allocation remains the source of truth; this queue reconciles eligible drivers and vehicles before dispatch." actions={<ActionButton tone="secondary" onClick={()=>router.push(selected?`/admin/diary?job=${selected}`:'/admin/diary')}>Open Diary</ActionButton>}/><KpiGrid><KpiCard label="Awarded, unallocated" value={jobs.filter(jobAwarded).length} tone="orange"/><KpiCard label="Awaiting acceptance" value={jobs.filter(jobAllocated).length} tone="purple"/><KpiCard label="Eligible drivers" value={eligibleDrivers.length} tone="green"/><KpiCard label="Eligible vehicles" value={eligibleVehicles.length} tone="blue"/></KpiGrid><Panel title="Allocation queue"><DataTable columns={['Load','Route','Pickup','Required vehicle','Driver capacity','Vehicle capacity','Action']} rows={jobs.map((job)=>[job.id.slice(0,8).toUpperCase(),<strong key="route">{route(job)}</strong>,when(job.pickup_datetime),label(job.vehicle_type),`${eligibleDrivers.length} eligible`,`${eligibleVehicles.length} eligible`,<ActionButton key="action" tone="success" onClick={()=>router.push(`/admin/diary?job=${job.id}`)}>Allocate in Diary</ActionButton>])} empty={<EmptyState title="No jobs awaiting allocation or acceptance"/>}/></Panel><TwoColumn><Panel title="Eligible drivers"><DataTable columns={['Driver','Availability','Compliance','Current job']} rows={data.drivers.map((driver)=>{const assignment=driverAssignedJob(driver,data.jobs);const ready=driverReady(driver,data.jobs,data.driverDocuments);return [driver.display_name??driver.email??'Driver',<StatusBadge key="availability" value={driver.availability_status??'not set'} tone={ready?'green':'orange'}/>,currentDocs(driverDocs(driver,data.driverDocuments))?'Current':'Action required',assignment?assignment.id.slice(0,8).toUpperCase():'None'];})}/></Panel><Panel title="Eligible vehicles"><DataTable columns={['Registration','Type','Driver relation','Compliance','Selectable']} rows={data.vehicles.map((vehicle)=>[vehicle.reg_plate??'Not recorded',label(vehicle.type),vehicle.assigned_driver_id?.slice(0,8).toUpperCase()??'Unassigned',<StatusBadge key="compliance" value={vehicleCompliance(vehicle,data.vehicleDocuments)} tone={vehicleCompliance(vehicle,data.vehicleDocuments)==='current'?'green':'orange'}/>,vehicleReady(vehicle,data.vehicleDocuments)?'Yes':'No'])}/></Panel></TwoColumn></PageFrame>;
}

export function FleetDriversView(){
 const data=useCompanyWorkspaceData(); const router=useRouter();
 return <PageFrame><PageHeader eyebrow="Fleet resources" title="Drivers" description="Persisted driver status, explicit availability, current assignment, latest signal and document readiness."/><KpiGrid><KpiCard label="Ready" value={data.drivers.filter((driver)=>driverReady(driver,data.jobs,data.driverDocuments)).length} tone="green"/><KpiCard label="Inactive" value={data.drivers.filter((driver)=>!driverActive(driver)).length} tone="red"/><KpiCard label="Assigned" value={data.drivers.filter((driver)=>Boolean(driverAssignedJob(driver,data.jobs))).length} tone="purple"/><KpiCard label="Compliance action" value={data.drivers.filter((driver)=>!currentDocs(driverDocs(driver,data.driverDocuments))).length} tone="orange"/></KpiGrid><Panel title="Driver register"><DataTable columns={['Driver','Account','Availability','Current job','Assigned vehicle','Latest signal','Compliance','Contact']} rows={data.drivers.map((driver)=>{const job=driverAssignedJob(driver,data.jobs);const vehicle=data.vehicles.find((item)=>item.assigned_driver_id===driver.id);const location=latestLocation(driver.id,data.locations);return [<strong key="driver">{driver.display_name??driver.email??'Driver'}</strong>,<StatusBadge key="account" value={driver.status??'unknown'}/>,<StatusBadge key="availability" value={driver.availability_status??'not set'} tone={driverReady(driver,data.jobs,data.driverDocuments)?'green':'orange'}/>,job?<button style={{border:0,background:'transparent',cursor:'pointer',textDecoration:'underline'}} onClick={()=>router.push(`/admin/jobs?job=${job.id}`)}>{job.id.slice(0,8).toUpperCase()}</button>:'None',vehicle?.reg_plate??'None',location?when(location.recorded_at??location.updated_at):'No signal',currentDocs(driverDocs(driver,data.driverDocuments))?'Current':'Action required',driver.phone?<a href={`tel:${driver.phone}`}>{driver.phone}</a>:driver.email??'Not recorded'];})} empty={<EmptyState title="No company drivers"/>}/></Panel></PageFrame>;
}

export function FleetVehiclesView(){
 const data=useCompanyWorkspaceData();
 return <PageFrame><PageHeader eyebrow="Fleet resources" title="Vehicles" description="Vehicle identity, driver relationship and persisted document compliance without defaulting every record to available."/><KpiGrid><KpiCard label="Allocation ready" value={data.vehicles.filter((vehicle)=>vehicleReady(vehicle,data.vehicleDocuments)).length} tone="green"/><KpiCard label="Assigned" value={data.vehicles.filter((vehicle)=>Boolean(vehicle.assigned_driver_id)).length} tone="purple"/><KpiCard label="Expired" value={data.vehicles.filter((vehicle)=>vehicleCompliance(vehicle,data.vehicleDocuments)==='expired').length} tone="red"/><KpiCard label="Compliance action" value={data.vehicles.filter((vehicle)=>vehicleCompliance(vehicle,data.vehicleDocuments)!=='current').length} tone="orange"/></KpiGrid><Panel title="Vehicle register"><DataTable columns={['Registration','Type','Make / model','Assigned driver','Compliance','Availability decision']} rows={data.vehicles.map((vehicle)=>{const driver=data.drivers.find((item)=>item.id===vehicle.assigned_driver_id);const compliance=vehicleCompliance(vehicle,data.vehicleDocuments);return [<strong key="reg">{vehicle.reg_plate??'Not recorded'}</strong>,label(vehicle.type),[vehicle.make,vehicle.model].filter(Boolean).join(' ')||'Not recorded',driver?.display_name??driver?.email??(vehicle.assigned_driver_id?'Assigned driver':'Unassigned'),<StatusBadge key="compliance" value={compliance} tone={compliance==='current'?'green':compliance==='expired'||compliance==='non-compliant'?'red':'orange'}/>,vehicleReady(vehicle,data.vehicleDocuments)?'Allocation ready':vehicle.assigned_driver_id?'Assigned':'Not selectable'];})} empty={<EmptyState title="No company vehicles"/>}/></Panel></PageFrame>;
}

type TrackingEvent={id:string;job_id:string;event_type:string;message?:string|null;created_at:string};
export function FleetActiveJobsView(){
 const data=useCompanyWorkspaceData(); const router=useRouter(); const search=useSearchParams(); const selectedId=search.get('job'); const selected=selectedId?data.jobs.find((job)=>job.id===selectedId):undefined; const [events,setEvents]=useState<TrackingEvent[]>([]); const [error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{if(!selected){setEvents([]);return;}const {data:rows,error:queryError}=await supabase.from('job_tracking_events').select('id,job_id,event_type,message,created_at').eq('job_id',selected.id).order('created_at',{ascending:true});if(cancelled)return;if(queryError){setError(queryError.message);setEvents([]);}else{setError('');setEvents((rows??[]) as TrackingEvent[]);}};void load();return()=>{cancelled=true};},[selected]);
 const jobs=data.jobs.filter((job)=>jobActive(job)||jobOverdue(job)||exceptionStages.has(statusOf(job))||['delivered','completed'].includes(statusOf(job)));
 return <PageFrame><PageHeader eyebrow="Fleet operations" title="Active Deliveries" description="Awarded, allocated, active and delivered stages remain distinct with persisted ETA, driver position and status history."/>{error&&<AlertBanner tone="danger">{error}</AlertBanner>}<Panel title="Delivery board"><DataTable columns={['Load','Route','Pickup','Delivery ETA','Driver','Lifecycle','Tracking','POD','Action']} rows={jobs.map((job)=>{const driver=data.drivers.find((item)=>item.id===job.assigned_driver_id);const location=job.assigned_driver_id?latestLocation(job.assigned_driver_id,data.locations):undefined;return [job.id.slice(0,8).toUpperCase(),<strong key="route">{route(job)}</strong>,when(job.pickup_datetime),<span key="eta" style={{color:jobOverdue(job)?workspaceTheme.red:workspaceTheme.text}}>{when(job.delivery_datetime)}{jobOverdue(job)?' · overdue':''}</span>,driver?.display_name??driver?.email??'Not assigned',<StatusBadge key="status" value={label(statusOf(job))}/>,location?<span key="signal">{location.lat.toFixed(5)}, {location.lng.toFixed(5)}<small style={{display:'block'}}>{when(location.recorded_at??location.updated_at)}</small></span>:'No signal',(job.delivery_photos?.length??0)>0?'POD present':'POD missing',<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/admin/fleet/active-jobs?job=${job.id}`)}>Details</ActionButton>];})} empty={<EmptyState title="No active or recently delivered jobs"/>}/></Panel>{selected&&<div style={{marginTop:'0.8rem'}}><Panel title={`Lifecycle · ${selected.id.slice(0,8).toUpperCase()}`}><ProgressSteps steps={lifecycle.map(label)} currentIndex={Math.max(lifecycle.indexOf(statusOf(selected)),0)}/></Panel><TwoColumn><Panel title="Tracking history"><DataTable columns={['Event','Time','Detail']} rows={events.map((event)=>[<StatusBadge key="event" value={label(event.event_type)} tone={exceptionStages.has(norm(event.event_type))?'red':undefined}/>,when(event.created_at),event.message??'—'])} empty={<EmptyState title="No tracking events recorded"/>}/></Panel><Panel title="Linked actions"><div style={{display:'grid',gap:'0.5rem'}}><ActionButton tone="secondary" onClick={()=>router.push(`/admin/jobs?job=${selected.id}`)}>Open Job</ActionButton><ActionButton tone="secondary" onClick={()=>router.push('/admin/documents')}>Open Documents</ActionButton><ActionButton tone="secondary" onClick={()=>router.push('/admin/invoices')}>Open Finance</ActionButton></div></Panel></TwoColumn></div>}</PageFrame>;
}

export function FleetPodView(){ return <PodDocumentsPage mode="broker"/>; }

export function FleetComplianceFinanceView(){
 const data=useCompanyWorkspaceData(); const router=useRouter(); const docs=data.driverDocuments.concat(data.vehicleDocuments); const issues=docs.filter((document)=>isExpired(document)||isExpiring(document)||isRejected(document));
 return <PageFrame><PageHeader eyebrow="Fleet control" title="Documents & Finance" description="Persisted compliance and carrier invoice actions linked back to Fleet operations." actions={<><ActionButton tone="secondary" onClick={()=>router.push('/admin/documents')}>All Documents</ActionButton><ActionButton tone="secondary" onClick={()=>router.push('/admin/invoices')}>All Invoices</ActionButton></>}/><KpiGrid><KpiCard label="Document issues" value={issues.length} tone="red"/><KpiCard label="Expired" value={docs.filter(isExpired).length} tone="red"/><KpiCard label="Expiring" value={docs.filter(isExpiring).length} tone="orange"/><KpiCard label="Unpaid invoices" value={data.invoices.filter((invoice)=>invoiceState(invoice)!=='paid').length} tone="navy"/><KpiCard label="Overdue invoices" value={data.invoices.filter(invoiceOverdue).length} tone="red"/></KpiGrid><TwoColumn><Panel title="Compliance queue"><DataTable columns={['Document','Resource','Status','Expiry','Issue']} rows={issues.map((document)=>[label(document.doc_type),document.driver_id?.slice(0,8).toUpperCase()??document.vehicle_id?.slice(0,8).toUpperCase()??'Company',<StatusBadge key="status" value={document.status??'unknown'}/>,document.expiry_date?new Date(document.expiry_date).toLocaleDateString('en-GB'):'Not set',isExpired(document)?'Expired':isRejected(document)?'Rejected':'Expiring'])} empty={<EmptyState title="No document action required"/>}/></Panel><Panel title="Finance queue"><DataTable columns={['Invoice','Job','Amount','Due','Status','Action']} rows={data.invoices.filter((invoice)=>invoiceState(invoice)!=='paid').map((invoice)=>[invoice.invoice_number??invoice.id.slice(0,8).toUpperCase(),invoice.job_id?.slice(0,8).toUpperCase()??'—',new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(invoice.amount??0)),invoice.due_date?new Date(invoice.due_date).toLocaleDateString('en-GB'):'Not set',<StatusBadge key="status" value={invoiceOverdue(invoice)?'Overdue':label(invoiceState(invoice))} tone={invoiceOverdue(invoice)?'red':'orange'}/>,invoice.job_id?<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/admin/jobs?job=${invoice.job_id}`)}>Open Job</ActionButton>:'—'])} empty={<EmptyState title="No unpaid carrier invoices"/>}/></Panel></TwoColumn></PageFrame>;
}
