export const mockLoads = [
  {
    id: 1,
    ref: 'XD-001',
    pickupLocation: 'Blackburn, UK',
    deliveryLocation: 'London, UK',
    vehicleType: 'luton',
    distanceKm: 232,
    priceGBP: 420,
    pickupTime: 'Today 13:30',
    deliveryTime: 'Today 20:00',
    loadType: 'Palletised goods',
    pallets: 8,
    weightKg: 1800,
    companyName: 'Prime Logistics Ltd',
  },
  {
    id: 2,
    ref: 'XD-002',
    pickupLocation: 'Manchester, UK',
    deliveryLocation: 'Birmingham, UK',
    vehicleType: 'xlwb',
    distanceKm: 140,
    priceGBP: 260,
    pickupTime: 'Today 15:00',
    deliveryTime: 'Today 19:00',
    loadType: 'Boxes',
    pallets: 4,
    weightKg: 950,
    companyName: 'Midlands Freight Co',
  },
  {
    id: 3,
    ref: 'XD-003',
    pickupLocation: 'Leeds, UK',
    deliveryLocation: 'Glasgow, UK',
    vehicleType: '7.5t',
    distanceKm: 320,
    priceGBP: 550,
    pickupTime: 'Tomorrow 08:00',
    deliveryTime: 'Tomorrow 18:00',
    loadType: 'Mixed pallets',
    pallets: 12,
    weightKg: 3500,
    companyName: 'Northern Haulage Group',
  },
  {
    id: 4,
    ref: 'XD-004',
    pickupLocation: 'Bristol, UK',
    deliveryLocation: 'Cardiff, UK',
    vehicleType: 'small-van',
    distanceKm: 70,
    priceGBP: 110,
    pickupTime: 'Today 11:00',
    deliveryTime: 'Today 14:00',
    loadType: 'Documents',
    pallets: 0,
    weightKg: 50,
    companyName: 'Legal Express',
  },
  {
    id: 5,
    ref: 'XD-005',
    pickupLocation: 'London, UK',
    deliveryLocation: 'Milton Keynes, UK',
    vehicleType: 'luton',
    distanceKm: 90,
    priceGBP: 210,
    pickupTime: 'Tomorrow 09:30',
    deliveryTime: 'Tomorrow 13:00',
    loadType: 'Retail stock',
    pallets: 6,
    weightKg: 1400,
    companyName: 'Retail Consolidators Ltd',
  },
];
