'use client';

export type SpreadsheetValue = string | number | boolean | Date | null | undefined;

export type SpreadsheetColumn = {
  header: string;
  key: string;
  width?: number;
  format?: 'text' | 'number' | 'currency' | 'date' | 'datetime';
};

export type SpreadsheetSheet = {
  name: string;
  title: string;
  subtitle?: string;
  columns: SpreadsheetColumn[];
  rows: Array<Record<string, SpreadsheetValue>>;
};

const MIME_XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

const safeSheetName = (value: string) =>
  value
    .replace(/[\\/?*:]/g, ' ')
    .replaceAll('[', ' ')
    .replaceAll(']', ' ')
    .trim()
    .slice(0, 31) || 'Report';

const downloadBlob = (blob: Blob, filename: string) => {
  const href = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = href;
  anchor.download = filename.toLowerCase().endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(href);
};

export async function downloadXlsx(filename: string, sheets: SpreadsheetSheet[]) {
  if (typeof window === 'undefined') return;

  const { Workbook } = await import('exceljs');
  const workbook = new Workbook();
  workbook.creator = 'XDrive Logistics';
  workbook.lastModifiedBy = 'XDrive Logistics';
  workbook.company = 'XDrive Logistics Ltd';
  workbook.created = new Date();
  workbook.modified = new Date();
  workbook.subject = 'XDrive Logistics operational and finance report';

  for (const spec of sheets) {
    const sheet = workbook.addWorksheet(safeSheetName(spec.name), {
      views: [{ state: 'frozen', ySplit: 4 }],
      properties: { defaultRowHeight: 18 },
      pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
    });

    const columnCount = Math.max(1, spec.columns.length);
    sheet.mergeCells(1, 1, 1, columnCount);
    sheet.getCell(1, 1).value = spec.title;
    sheet.getCell(1, 1).font = { bold: true, size: 16, color: { argb: 'FF0B2F6B' } };
    sheet.getCell(1, 1).alignment = { vertical: 'middle', horizontal: 'left' };
    sheet.getRow(1).height = 28;

    sheet.mergeCells(2, 1, 2, columnCount);
    sheet.getCell(2, 1).value = spec.subtitle || `Generated by XDrive Logistics · ${new Date().toLocaleString('en-GB')}`;
    sheet.getCell(2, 1).font = { size: 9, color: { argb: 'FF64748B' } };

    sheet.columns = spec.columns.map((column) => ({
      key: column.key,
      width: column.width ?? 18,
    }));

    const headerRow = sheet.getRow(4);
    spec.columns.forEach((column, index) => {
      const cell = headerRow.getCell(index + 1);
      cell.value = column.header;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0B2F6B' } };
      cell.alignment = { vertical: 'middle', horizontal: 'left' };
      cell.border = { bottom: { style: 'thin', color: { argb: 'FFF5A300' } } };
    });
    headerRow.height = 22;

    spec.rows.forEach((row, rowIndex) => {
      const worksheetRow = sheet.addRow(row);
      worksheetRow.alignment = { vertical: 'top' };

      spec.columns.forEach((column, index) => {
        const cell = worksheetRow.getCell(index + 1);
        if (column.format === 'currency') cell.numFmt = '£#,##0.00;[Red](£#,##0.00);-';
        if (column.format === 'number') cell.numFmt = '#,##0.00;[Red](#,##0.00);-';
        if (column.format === 'date') cell.numFmt = 'dd/mm/yyyy';
        if (column.format === 'datetime') cell.numFmt = 'dd/mm/yyyy hh:mm';
        cell.alignment = { vertical: 'top', wrapText: true };
      });

      if (rowIndex % 2 === 1) {
        worksheetRow.eachCell((cell) => {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
        });
      }
    });

    if (spec.rows.length > 0 && spec.columns.length > 0) {
      sheet.autoFilter = {
        from: { row: 4, column: 1 },
        to: { row: 4, column: spec.columns.length },
      };
    }

    sheet.getColumn(1).alignment = { vertical: 'top', horizontal: 'left' };
    sheet.pageSetup.margins = {
      left: 0.25,
      right: 0.25,
      top: 0.5,
      bottom: 0.5,
      header: 0.2,
      footer: 0.2,
    };
    sheet.headerFooter.oddFooter = 'XDrive Logistics Ltd · &P / &N';
  }

  const buffer = await workbook.xlsx.writeBuffer();
  downloadBlob(new Blob([buffer as BlobPart], { type: MIME_XLSX }), filename);
}

export const spreadsheetDate = (value: string | null | undefined): Date | null => {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
};

export async function readXlsxSheetRows(buffer: ArrayBuffer, sheetName: string): Promise<string[][]> {
  const { Workbook } = await import('exceljs');
  const workbook = new Workbook();
  await workbook.xlsx.load(buffer);
  const sheet = workbook.getWorksheet(sheetName);
  if (!sheet) throw new Error(`The workbook does not contain the required ${sheetName} sheet.`);

  const rows: string[][] = [];
  for (let rowNumber = 1; rowNumber <= sheet.rowCount; rowNumber += 1) {
    const row = sheet.getRow(rowNumber);
    const values: string[] = [];
    for (let columnNumber = 1; columnNumber <= row.cellCount; columnNumber += 1) {
      const cell = row.getCell(columnNumber);
      if (cell.value instanceof Date) {
        const year = cell.value.getFullYear();
        const month = String(cell.value.getMonth() + 1).padStart(2, '0');
        const day = String(cell.value.getDate()).padStart(2, '0');
        values.push(`${year}-${month}-${day}`);
      } else {
        values.push(cell.text?.trim() || (cell.value == null ? '' : String(cell.value).trim()));
      }
    }
    rows.push(values);
  }
  return rows;
}
