'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';
import LoadPostingForm from '../components/workspace/LoadPostingForm';
import { useCompanyWorkspaceData } from '../components/workspace/useCompanyWorkspaceData';
import { ActionButton, AlertBanner, DataTable, EmptyState, PageFrame, PageHeader, Panel, StatusBadge } from '../components/workspace/WorkspaceUI';
import { currentStatus, isActiveDelivery, isAwardedPending, lifecycleLabel, money, quotePrice, routeLabel, submittedQuotes, when } from './BrokerDashboardView';

export function BrokerCustomersPage(){
 const router=useRouter(); const data=useCompanyWorkspaceData();
 const customers=useMemo(()=>{const map=new Map<string,{name:string;jobs:number;active:number;revenue:number;last:string}>(); for(const job of data.jobs){const name=job.client_name?.trim()||'Unassigned customer'; const current=map.get(name)??{name,jobs:0,active:0,revenue:0,last:job.updated_at}; current.jobs+=1; current.active+=isActiveDelivery(job)?1:0; current.revenue+=Number(job.budget_amount??0); if(job.updated_at>current.last)current.last=job.updated_at; map.set(name,current);} return [...map.values()].sort((a,b)=>b.last.localeCompare(a.last));},[data.jobs]);
 return <PageFrame><PageHeader eyebrow="Broker customers" title="Customers" description="Customer relationships derived only from broker-managed loads and persisted commercial activity." actions={<ActionButton tone="warning" onClick={()=>router.push('/broker/post-load')}>Create Load</ActionButton>}/><Panel title="Customer book"><DataTable columns={['Customer','Loads','Active jobs','Revenue','Last activity','Action']} rows={customers.map((customer)=>[<strong key="name">{customer.name}</strong>,customer.jobs,customer.active,money(customer.revenue),when(customer.last),<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/broker/loads?customer=${encodeURIComponent(customer.name)}`)}>View loads</ActionButton>])} empty={<EmptyState title="No customers yet"/>}/></Panel></PageFrame>;
}

export function BrokerLoadsPage(){
 const router=useRouter(); const data=useCompanyWorkspaceData();
 return <PageFrame><PageHeader eyebrow="Customer loads" title="Customer Loads" description="Broker-managed transport requests remain company-scoped and connected to their submitted carrier quotes." actions={<ActionButton tone="warning" onClick={()=>router.push('/broker/post-load')}>Post Load</ActionButton>}/>{data.error&&<AlertBanner>{data.error}</AlertBanner>}<Panel title="Load register"><DataTable columns={['Reference','Customer','Route','Pickup','Vehicle','Price','Quotes','Lifecycle','Action']} rows={data.jobs.map((job)=>[job.id.slice(0,8).toUpperCase(),job.client_name??'Customer',<strong key="route">{routeLabel(job)}</strong>,when(job.pickup_datetime),lifecycleLabel(job.vehicle_type??'Not specified'),money(Number(job.budget_amount??0)),submittedQuotes(data.bids,job.id).length,<StatusBadge key="status" value={lifecycleLabel(currentStatus(job))}/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/broker/compare-quotes?job=${job.id}`)}>{submittedQuotes(data.bids,job.id).length?'Compare':'Open'}</ActionButton>])} empty={<EmptyState title="No customer loads" action={<ActionButton tone="warning" onClick={()=>router.push('/broker/post-load')}>Post first load</ActionButton>}/>} /></Panel></PageFrame>;
}

export function BrokerPostLoadPage(){return <PageFrame><PageHeader eyebrow="Customer load" title="Post Load" description="Create the customer transport request using the existing broker posting workflow."/><LoadPostingForm mode="broker"/></PageFrame>}

export function BrokerQuotesPage({compare=false}:{compare?:boolean}){
 const data=useCompanyWorkspaceData(); const router=useRouter(); const [working,setWorking]=useState<string|null>(null); const [message,setMessage]=useState('');
 const grouped=useMemo(()=>data.jobs.map((job)=>({job,quotes:data.bids.filter((bid)=>bid.job_id===job.id&&['submitted','accepted','rejected'].includes(bid.status))})).filter((group)=>group.quotes.length>0),[data.jobs,data.bids]);
 const award=async(bidId:string)=>{setWorking(bidId);setMessage('');const {data:session}=await supabase.auth.getSession();const response=await fetch(`/api/customer/bids/${bidId}/award`,{method:'POST',headers:session.session?.access_token?{Authorization:`Bearer ${session.session.access_token}`}:{}});const payload=await response.json().catch(()=>({})) as {error?:string};setWorking(null);if(!response.ok){setMessage(payload.error??'Unable to award this carrier quote.');return;}setMessage('Carrier quote awarded successfully.');await data.refresh();};
 return <PageFrame><PageHeader eyebrow="Carrier sourcing" title={compare?'Compare Quotes':'Carrier Quotes'} description={compare?'Compare real carrier price, vehicle context, submitted time and persisted customer revenue before award.':'All submitted carrier responses linked to broker-managed loads.'} actions={<ActionButton tone="secondary" onClick={()=>router.push(compare?'/broker/bids':'/broker/compare-quotes')}>{compare?'All Quotes':'Compare'}</ActionButton>}/>{message&&<AlertBanner tone={message.includes('successfully')?'success':'danger'}>{message}</AlertBanner>}{grouped.map(({job,quotes})=>{const pickupRisk=job.pickup_datetime&&new Date(job.pickup_datetime).getTime()-Date.now()<=86400000&&!job.awarded_carrier_company_id;return <Panel key={job.id} title={routeLabel(job)} description={`${job.client_name??'Customer'} · pickup ${when(job.pickup_datetime)}`} style={{marginBottom:'0.8rem'}}>{pickupRisk&&<AlertBanner tone="warning">Pickup is approaching and a carrier decision is still outstanding.</AlertBanner>}<DataTable columns={compare?['Carrier','Quote','Vehicle / note','Submitted','Customer revenue','Gross margin','Status','Decision']:['Carrier','Quote','Vehicle / note','Submitted','Status','Decision']} rows={quotes.slice().sort((a,b)=>quotePrice(a)-quotePrice(b)).map((bid)=>{const cost=quotePrice(bid);const revenue=Number(job.budget_amount??0);const margin=revenue-cost;const note=bid.message??'No vehicle or timing note supplied';return compare?[bid.companies?.name??'Carrier',money(cost),note,when(bid.created_at),money(revenue),revenue>0?`${money(margin)} · ${((margin/revenue)*100).toFixed(1)}%`:'Not available',<StatusBadge key="status" value={lifecycleLabel(bid.status)}/>,bid.status==='submitted'?<ActionButton key="award" tone="success" disabled={working===bid.id} onClick={()=>void award(bid.id)}>{working===bid.id?'Awarding…':'Award'}</ActionButton>:'—']:[bid.companies?.name??'Carrier',money(cost),note,when(bid.created_at),<StatusBadge key="status" value={lifecycleLabel(bid.status)}/>,bid.status==='submitted'?<ActionButton key="award" tone="success" disabled={working===bid.id} onClick={()=>void award(bid.id)}>{working===bid.id?'Awarding…':'Award'}</ActionButton>:'—'];})}/></Panel>})}{grouped.length===0&&<Panel><EmptyState title="No carrier quotes received"/></Panel>}</PageFrame>;
}

export function BrokerAwardsPage(){const data=useCompanyWorkspaceData();const router=useRouter();const rows=data.jobs.filter(isAwardedPending);return <PageFrame><PageHeader eyebrow="Carrier awards" title="Awards" description="Carrier selected, but transport has not yet entered an accepted or active delivery stage."/><Panel title="Award register"><DataTable columns={['Load','Customer','Route','Pickup','Lifecycle','Allocation','Action']} rows={rows.map((job)=>[job.id.slice(0,8).toUpperCase(),job.client_name??'Customer',routeLabel(job),when(job.pickup_datetime),<StatusBadge key="status" value={lifecycleLabel(currentStatus(job))}/>,job.assigned_driver_id?<StatusBadge key="allocation" value="Driver allocated" tone="green"/>:<StatusBadge key="allocation" value="Allocation incomplete" tone="orange"/>,<ActionButton key="action" tone="secondary" onClick={()=>router.push(`/broker/jobs?job=${job.id}`)}>Track</ActionButton>])} empty={<EmptyState title="No awarded loads awaiting operational start"/>}/></Panel></PageFrame>}
