'use client';

import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';
import { useCompanyWorkspaceData } from '../components/workspace/useCompanyWorkspaceData';
import { AlertBanner, DataTable, EmptyState, KpiCard, KpiGrid, PageFrame, PageHeader, Panel, ProgressSteps, StatusBadge, TwoColumn, workspaceTheme } from '../components/workspace/WorkspaceUI';
import { currentStatus, isActiveDelivery, isOverdue, latestLocation, lifecycleLabel, lifecycleStages, routeLabel, stageIndex, when } from './BrokerDashboardView';

type TrackingEvent={id:string;job_id:string;event_type:string;message?:string|null;created_at:string};
type BrokerDispute={id:string;job_id:string;raised_by_company_id:string;status:string;description:string|null;resolution_note:string|null;created_at:string};
const exceptionToken=(value:string)=>['incident','waiting','cancel','failed','dispute','exception'].some((token)=>value.toLowerCase().includes(token));

export function BrokerJobsPage(){
 const data=useCompanyWorkspaceData(); const searchParams=useSearchParams(); const selectedId=searchParams.get('job');
 const jobs=data.jobs.filter((job)=>isActiveDelivery(job)||['delivered','completed'].includes(currentStatus(job))||exceptionToken(currentStatus(job)));
 const selected=selectedId?data.jobs.find((job)=>job.id===selectedId)??null:null;
 const [events,setEvents]=useState<TrackingEvent[]>([]); const [error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{if(!selected?.id){setEvents([]);return;}const {data:rows,error:queryError}=await supabase.from('job_tracking_events').select('id,job_id,event_type,message,created_at').eq('job_id',selected.id).order('created_at',{ascending:true});if(cancelled)return;if(queryError){setError(queryError.message);setEvents([]);}else{setError('');setEvents((rows??[]) as TrackingEvent[]);}};void load();return()=>{cancelled=true};},[selected?.id]);
 const location=selected?latestLocation(selected,data.locations):undefined; const exceptions=events.filter((event)=>exceptionToken(event.event_type));
 return <PageFrame><PageHeader eyebrow="Broker operations" title="Active Jobs" description="Track accepted transport through collection, delivery, ETA, latest driver signal and persisted status history."/>{data.error&&<AlertBanner>{data.error}</AlertBanner>}{error&&<AlertBanner tone="danger">{error}</AlertBanner>}
 <Panel title="Operational job board"><DataTable columns={['Load','Route','Pickup','Delivery ETA','Lifecycle','Tracking','POD']} rows={jobs.map((job)=>{const signal=latestLocation(job,data.locations);return [job.id.slice(0,8).toUpperCase(),<strong key="route">{routeLabel(job)}</strong>,when(job.pickup_datetime),<span key="eta" style={{color:isOverdue(job)?workspaceTheme.red:workspaceTheme.text,fontWeight:isOverdue(job)?800:500}}>{when(job.delivery_datetime)}{isOverdue(job)?' · overdue':''}</span>,<StatusBadge key="status" value={lifecycleLabel(currentStatus(job))}/>,signal?<span key="tracking"><strong style={{display:'block'}}>{signal.lat.toFixed(5)}, {signal.lng.toFixed(5)}</strong><small style={{color:workspaceTheme.muted}}>{when(signal.recorded_at??signal.updated_at)}</small></span>:'No live signal',(job.delivery_photos?.length??0)>0?<StatusBadge key="pod" value="POD available" tone="green"/>:<StatusBadge key="pod" value="Awaiting POD" tone="orange"/>];})} empty={<EmptyState title="No active or completed jobs"/>}/></Panel>
 {selected&&<div style={{marginTop:'0.8rem'}}><Panel title={`Job ${selected.id.slice(0,8).toUpperCase()} · ${routeLabel(selected)}`} description={`Pickup ${when(selected.pickup_datetime)} · ETA ${when(selected.delivery_datetime)}`}><ProgressSteps steps={lifecycleStages.map(lifecycleLabel)} currentIndex={stageIndex(selected)}/></Panel><TwoColumn><Panel title="Tracking timeline"><DataTable columns={['Event','Time','Detail']} rows={events.map((event)=>[<StatusBadge key="event" value={lifecycleLabel(event.event_type)} tone={exceptionToken(event.event_type)?'red':undefined}/>,when(event.created_at),event.message??'—'])} empty={<EmptyState title="No tracking events recorded"/>}/></Panel><div style={{display:'grid',gap:'0.8rem'}}><Panel title="Latest tracking signal"><div style={{display:'grid',gap:'0.5rem',fontSize:'0.75rem'}}><div><span style={{color:workspaceTheme.muted}}>Scheduled ETA</span><strong style={{display:'block'}}>{when(selected.delivery_datetime)}</strong></div><div><span style={{color:workspaceTheme.muted}}>Latest coordinates</span><strong style={{display:'block'}}>{location?`${location.lat.toFixed(5)}, ${location.lng.toFixed(5)}`:'Not available'}</strong></div><div><span style={{color:workspaceTheme.muted}}>Last signal</span><strong style={{display:'block'}}>{location?when(location.recorded_at??location.updated_at):'Not available'}</strong></div></div></Panel><Panel title="Exceptions"><DataTable columns={['Type','Time','Detail']} rows={exceptions.map((event)=>[<StatusBadge key="type" value={lifecycleLabel(event.event_type)} tone="red"/>,when(event.created_at),event.message??'No detail recorded'])} empty={<EmptyState title="No operational exceptions recorded"/>}/></Panel></div></TwoColumn></div>}
 </PageFrame>;
}

export function BrokerDisputesPage(){
 const data=useCompanyWorkspaceData(); const [rows,setRows]=useState<BrokerDispute[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{if(!data.companyId){if(!cancelled){setRows([]);setLoading(false);}return;}setLoading(true);setError('');const jobIds=data.jobs.map((job)=>job.id);let query=supabase.from('job_disputes').select('id,job_id,raised_by_company_id,status,description,resolution_note,created_at').order('created_at',{ascending:false}).limit(250);query=jobIds.length>0?query.or(`raised_by_company_id.eq.${data.companyId},job_id.in.(${jobIds.join(',')})`):query.eq('raised_by_company_id',data.companyId);const {data:result,error:queryError}=await query;if(cancelled)return;if(queryError){setError(queryError.message);setRows([]);}else setRows((result??[]) as BrokerDispute[]);setLoading(false);};void load();return()=>{cancelled=true};},[data.companyId,data.jobs]);
 const counts=useMemo(()=>({open:rows.filter((row)=>row.status==='open').length,investigating:rows.filter((row)=>row.status==='investigating').length,resolved:rows.filter((row)=>['resolved','closed'].includes(row.status)).length}),[rows]);
 return <PageFrame><PageHeader eyebrow="Commercial exceptions" title="Disputes" description="Customer, carrier and POD disputes linked only to broker-managed loads."/>{error&&<AlertBanner tone="danger">{error}</AlertBanner>}<KpiGrid><KpiCard label="Open" value={counts.open} tone="red"/><KpiCard label="Investigating" value={counts.investigating} tone="orange"/><KpiCard label="Resolved" value={counts.resolved} tone="green"/></KpiGrid><Panel title="Dispute register"><DataTable columns={['Job','Raised by','Issue','Opened','Status','Resolution']} rows={rows.map((row)=>[row.job_id.slice(0,8).toUpperCase(),row.raised_by_company_id===data.companyId?'Broker company':'Trading partner',row.description??'No description recorded',when(row.created_at),<StatusBadge key="status" value={lifecycleLabel(row.status)}/>,row.resolution_note??'Pending'])} empty={<EmptyState title={loading?'Loading disputes…':'No disputes found'}/>} /></Panel></PageFrame>;
}
