#!/usr/bin/env node

// The canonical operations validator is generated by the shared runner so both
// staging lanes use canonical profile roles and persist real POD evidence in
// the private pod-docs bucket before submitting the POD API request.
import './run_remote_staging_operational_journey.mjs';
