create table if not exists public.driver_mobile_device_sessions (
  installation_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  auth_session_id uuid not null,
  platform text not null default 'android' check (platform = 'android'),
  app_package text not null default 'co.uk.xdrivelogistics.driver',
  device_label text,
  enabled boolean not null default true,
  registered_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (auth_session_id)
);

create unique index if not exists driver_mobile_one_active_device_per_driver_uidx
  on public.driver_mobile_device_sessions (driver_id)
  where enabled = true and revoked_at is null;

create index if not exists driver_mobile_device_user_idx
  on public.driver_mobile_device_sessions (user_id, last_seen_at desc);

alter table public.driver_mobile_device_sessions enable row level security;
revoke all on table public.driver_mobile_device_sessions from anon, authenticated;
grant all on table public.driver_mobile_device_sessions to service_role;

comment on table public.driver_mobile_device_sessions is
  'Server-only binding between a named driver, one native Android installation and one validated Supabase auth session. Newest native login wins; older bindings are revoked.';
comment on column public.driver_mobile_device_sessions.installation_id is
  'Random per-install UUID generated by the native app. This is not a hardware fingerprint.';
comment on column public.driver_mobile_device_sessions.auth_session_id is
  'Validated JWT session_id. Device authorization is valid only for this exact authenticated session.';
