-- Align the historical invoice-number trigger with the canonical per-company
-- numbering contract used by current server routes: INV-YYYYMM-NNN.
--
-- The completion trigger must remain enabled for now because at least one
-- existing Workspace path can still persist an allowed jobs.status transition
-- directly. This migration therefore does NOT remove invoice generation. It
-- only removes the old XDR-xxxxx sequence fallback from trigger-owned inserts.
-- Existing invoice numbers are immutable and are not rewritten.

BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

DO $$
BEGIN
  IF to_regprocedure('public.next_invoice_number(uuid)') IS NULL THEN
    RAISE EXCEPTION 'Canonical public.next_invoice_number(uuid) is required before invoice trigger reconciliation.'
      USING ERRCODE = '42883';
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.generate_invoice_number()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  -- Respect a number already generated by a canonical server creation path.
  -- Trigger-owned inserts (including completion-trigger inserts) pass NULL and
  -- are assigned through the same canonical per-company RPC contract.
  IF NULLIF(btrim(COALESCE(NEW.invoice_number, '')), '') IS NULL THEN
    IF NEW.company_id IS NULL THEN
      RAISE EXCEPTION 'Invoice company_id is required before invoice-number generation.'
        USING ERRCODE = '23502';
    END IF;

    NEW.invoice_number := public.next_invoice_number(NEW.company_id);

    IF NULLIF(btrim(COALESCE(NEW.invoice_number, '')), '') IS NULL THEN
      RAISE EXCEPTION 'Canonical invoice-number generation returned no value.'
        USING ERRCODE = '23514';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.generate_invoice_number() IS
  'Compatibility trigger function. NULL invoice numbers are generated through canonical next_invoice_number(uuid); pre-generated canonical numbers are preserved.';

COMMIT;
