begin;

alter function public.accept_bid(uuid, uuid) set search_path to public, pg_temp;
alter function public.assign_job_customer_ref() set search_path to public, pg_temp;
alter function public.assign_xd_company_id() set search_path to public, pg_temp;
alter function public.assign_xd_user_id() set search_path to public, pg_temp;
alter function public.coalesce_driver_full_name() set search_path to public, pg_temp;
alter function public.coalesce_driver_name() set search_path to public, pg_temp;
alter function public.current_company_id() set search_path to public, pg_temp;
alter function public.enforce_asap_direct_delivery() set search_path to public, pg_temp;
alter function public.fn_calculate_invoice_payment_status(numeric, numeric) set search_path to public, pg_temp;
alter function public.fn_job_bids_fill_bid_price_gbp() set search_path to public, pg_temp;
alter function public.fn_notification_event_body(text, jsonb) set search_path to public, pg_temp;
alter function public.fn_notification_event_title(text) set search_path to public, pg_temp;
alter function public.generate_xd_company_id() set search_path to public, pg_temp;
alter function public.generate_xd_user_id() set search_path to public, pg_temp;
alter function public.is_company_admin_of(uuid, uuid) set search_path to public, pg_temp;
alter function public.is_owner(uuid) set search_path to public, pg_temp;
alter function public.job_bids_fill_quote_amount() set search_path to public, pg_temp;
alter function public.normalize_doc_type(text) set search_path to public, pg_temp;
alter function public.normalize_profile_role(text, text) set search_path to public, pg_temp;
alter function public.prevent_unsafe_driver_delete() set search_path to public, pg_temp;
alter function public.set_company_settings_updated_at() set search_path to public, pg_temp;
alter function public.set_updated_at() set search_path to public, pg_temp;
alter function public.support_tickets_set_timestamps() set search_path to public, pg_temp;
alter function public.sync_job_assignment_from_accepted_bid() set search_path to public, pg_temp;
alter function public.tg_job_bids_fill_bid_price_gbp() set search_path to public, pg_temp;
alter function public.touch_job_disputes_updated_at() set search_path to public, pg_temp;
alter function public.touch_platform_settings_updated_at() set search_path to public, pg_temp;
alter function public.touch_updated_at_company_documents() set search_path to public, pg_temp;
alter function public.touch_updated_at_generic() set search_path to public, pg_temp;
alter function public.update_invoices_updated_at() set search_path to public, pg_temp;
alter function public.update_timestamp_function() set search_path to public, pg_temp;
alter function public.update_updated_at_column() set search_path to public, pg_temp;

commit;
