import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, CheckCircle2 } from 'lucide-react';

const plans = [
  { id: 'owner-driver', role: 'owner_operator', name: 'Owner Driver', price: '£29.99', detail: '1 self-employed courier / owner driver', features: ['3 months free', 'Exchange access', 'Quote workflow', 'Awarded jobs', 'Live status & POD'] },
  { id: 'customer-shipper', role: 'customer_shipper', name: 'Customer / Shipper', price: '£29.99', detail: 'Businesses posting and managing transport work', features: ['3 months free', 'Post transport work', 'Compare quotes', 'Award jobs', 'Track through POD'] },
  { id: 'small-carrier', role: 'fleet_operator', name: 'Small Carrier', price: '£59.99', detail: '2–5 vehicle operations', features: ['3 months free', 'Exchange access', 'Driver allocation', 'Operational records', 'POD & invoice readiness'] },
  { id: 'broker', role: 'transport_broker', name: 'Broker', price: '£79.99', detail: 'Posting and managing transport work for customers', features: ['3 months free', 'Post jobs', 'Compare quotes', 'Award work', 'Track through POD'], featured: true },
  { id: 'growing-carrier', role: 'fleet_operator', name: 'Growing Carrier', price: '£89.99', detail: '6–15 vehicle operations', features: ['3 months free', 'Exchange access', 'Multi-driver operations', 'Dispatch workflow', 'POD & finance readiness'] },
  { id: 'fleet', role: 'fleet_operator', name: 'Fleet', price: '£149.99', detail: '16–50 vehicle operations', features: ['3 months free', 'Fleet operations', 'Exchange & dispatch', 'POD records', 'Operational visibility'] },
  { id: 'enterprise', role: 'fleet_operator', name: 'Enterprise', price: 'From £249.99', detail: 'Larger or custom transport operations', features: ['3 months free', 'Custom operational scope', 'Larger user/fleet needs', 'Advanced onboarding', 'Commercial review'] },
] as const;

export default function PricingPage() {
  return <div className="min-h-screen bg-[#F7F9FC] text-[#102447]">
    <header className="sticky top-0 z-50 border-b border-[#E2E8F1] bg-white/95 backdrop-blur-xl">
      <div className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-5 sm:px-8">
        <Link href="/"><Image src="/xdrive-logo-primary.png" alt="XDrive Logistics" width={218} height={59} priority className="h-[44px] w-auto" /></Link>
        <nav className="hidden items-center gap-6 text-sm font-black text-[#48607E] lg:flex"><Link href="/platform">Platform</Link><Link href="/brokers">Brokers</Link><Link href="/couriers">Couriers</Link><Link href="/pricing">Pricing</Link><Link href="/access">Access</Link><Link href="/login">Sign In</Link></nav>
        <Link href="/register" className="rounded-lg bg-[#0E3FA9] px-5 py-2.5 text-sm font-black text-white">Start Free</Link>
      </div>
    </header>
    <main>
      <section className="bg-white px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-[1240px]"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#F5A300]">XDrive Membership</p><h1 className="mt-5 max-w-5xl text-[3.2rem] font-black leading-[0.96] tracking-tight text-[#0A234F] sm:text-[4.8rem]">Simple pricing. First 3 months free.</h1><p className="mt-7 max-w-3xl text-lg font-semibold leading-8 text-[#516987]">No XDrive commission on the value of your job. No XDrive booking fee. After your free period, continue on the plan that matches your operation.</p><div className="mt-6 rounded-xl border border-[#E2E8F1] bg-[#F7F9FC] p-5 text-sm font-bold leading-6 text-[#516987]"><p>Launch plans are monthly rolling after the free period. Public prices shown are exclusive of VAT unless expressly stated otherwise; VAT is added where legally applicable. There is no minimum paid term under the standard monthly launch model.</p><p className="mt-2">A paid membership should not begin until the applicable plan, billing date and renewal amount are presented and accepted. See the <Link href="/subscription-terms" className="font-black text-[#0E3FA9] underline">Membership & Subscription Terms</Link> for renewal, cancellation and refund rules.</p></div></div></section>
      <section className="px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-[1240px] gap-5 md:grid-cols-2 xl:grid-cols-3">{plans.map(plan => <article key={plan.id} className={`relative flex min-h-[430px] flex-col rounded-2xl border bg-white p-7 shadow-[0_18px_50px_rgba(8,38,86,0.06)] ${'featured' in plan && plan.featured ? 'border-[#0E3FA9] ring-2 ring-[#0E3FA9]/10' : 'border-[#E2E8F1]'}`}>{'featured' in plan && plan.featured ? <div className="absolute right-0 top-0 rounded-bl-xl bg-[#F5A300] px-4 py-2 text-[0.68rem] font-black uppercase tracking-[0.12em] text-[#0A234F]">Broker plan</div> : null}<p className="text-xs font-black uppercase tracking-[0.14em] text-[#5D7594]">{plan.name}</p><div className="mt-5 text-4xl font-black text-[#0A234F]">{plan.price}<span className="text-sm font-bold text-[#6A7C95]"> / month + VAT</span></div><p className="mt-3 text-sm font-semibold text-[#60758F]">{plan.detail}</p><div className="mt-4 inline-flex w-fit rounded-full bg-[#FFF5DB] px-3 py-1.5 text-xs font-black uppercase tracking-[0.08em] text-[#8A6100]">First 3 months free</div><div className="mt-6 grid gap-3">{plan.features.map(feature => <div key={feature} className="flex items-start gap-3 text-sm font-bold text-[#385475]"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#1E7A43]" />{feature}</div>)}</div><Link href={`/register?role=${plan.role}&plan=${plan.id}`} className={`mt-auto flex items-center justify-between rounded-lg px-4 py-3 text-sm font-black ${'featured' in plan && plan.featured ? 'bg-[#0E3FA9] text-white' : 'border border-[#D8E1ED] text-[#0E3FA9]'}`}>Apply for free access <ArrowRight className="h-4 w-4" /></Link></article>)}</div><div className="mx-auto mt-10 grid max-w-[1240px] gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-gradient-to-br from-[#071B3C] to-[#0B2F6B] p-7 text-white sm:p-9"><h2 className="text-3xl font-black">What makes the launch offer different?</h2><p className="mt-4 font-semibold leading-7 text-white/70">You get three months to use XDrive before paid membership begins. The platform does not take a percentage of your transport fee and does not add an XDrive booking fee to the job.</p></div><div className="rounded-2xl border border-[#E2E8F1] bg-white p-7 sm:p-9"><h2 className="text-3xl font-black text-[#0A234F]">Cancellation and renewal</h2><p className="mt-4 font-semibold leading-7 text-[#60758F]">Standard launch membership is monthly rolling after the free period. Cancel future renewal through the available account process or by contacting XDrive if self-service cancellation is unavailable. Any mandatory statutory rights continue to apply where relevant.</p><Link href="/subscription-terms" className="mt-5 inline-flex items-center gap-2 font-black text-[#0E3FA9]">Read membership terms <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </main>
  </div>;
}
